module.exports = [
"Bang for your buck",
"bird in the hand",
"bunch of fives",
"diamond in the rough",
"diamond is forever",
"dog is a man's best friend",
"drop in the bucket",
"drop in the ocean",
"feather in one's cap",
"fish out of water",
"fly in the ointment",
"fool's paradise",
"foot in the door",
"foregone conclusion",
"load of codswallop",
"nation of shopkeepers",
"nest of vipers",
"piece of the action",
"pig in a poke",
"sea change",
"skeleton in the closet",
"shot in the arm",
"sorry sight",
"stone's throw",
"tinker's damn",
"word in edgeways",
"About face",
"About turn",
"Above board",
"Absent without leave",
"Accidentally on purpose",
"Accidents will happen",
"According to Hoyle",
"Ace in the hole",
"Achilles' heel",
"Acid test",
"Across the board",
"Act of God",
"Act the giddy goat",
"Action man",
"Adam's ale",
"Aga saga",
"Against the grain",
"Age before beauty",
"Agree to disagree",
"Aid and abet",
"Aide mémoire",
"Air kiss",
"Air quotes",
"Al fresco",
"Alike as two peas in a pod",
"Alive and kicking",
"All agog",
"All at sea",
"All fingers and thumbs",
"All in all",
"All intents and purposes",
"All of a sudden",
"All present and correct",
"All singing, all dancing",
"All things must pass",
"All you can eat",
"Alter ego",
"Amber nectar",
"An arm and a leg",
"An ill wind",
"An offer he can't refuse",
"An Oxford scholar",
"Anchors aweigh",
"Angry young man",
"Ankle biter",
"Annus horribilis",
"Another think coming",
"Apple of my eye",
"Apple pie order",
"April fool",
"Arm candy",
"Arms akimbo",
"Ars longa, vita brevis",
"Arty farty",
"As bald as a coot",
"As brown as a berry",
"As busy as a bee",
"As cold as any stone",
"As cool as a cucumber",
"As cute as a bug's ear",
"As daft as a brush",
"As dead as a dodo",
"As dead as a doornail",
"As easy as pie",
"As fine as frog's hair",
"As fit as a butcher's dog",
"As fit as a fiddle",
"As good as gold",
"As good luck would have it",
"As happy as a clam",
"As happy as a sandboy",
"As happy as Larry",
"As keen as mustard",
"As mad as a hatter",
"As mad as a March hare",
"As nice as ninepence",
"As old as Methuselah",
"As old as the hills",
"As pleased as Punch",
"As pure as the driven snow",
"As snug as a bug in a rug",
"As straight as a die",
"As the crow flies",
"As white as snow",
"At loggerheads",
"At one fell swoop",
"At one's beck and call",
"At sixes and sevens",
"Auld lang syne",
"Away with the fairies",
"Baby blues",
"Baby boomer",
"Baby father",
"Back of beyond",
"Back seat driver",
"Back the field",
"Back to basics",
"Back to square one",
"Back to the drawing board",
"Backroom boy",
"Bad books",
"Bad egg",
"Bad hair day",
"Badger to death",
"Bag and baggage",
"Baker's dozen",
"Balance of power",
"Balance of trade",
"Bald as a coot",
"Bale out/bail out",
"Ball and chain",
"Bandy words",
"Bane of your life",
"Bang on about",
"Baptism of fire",
"Barking mad",
"Barking up the wrong tree",
"Basket case",
"Bated breath",
"Bats in the belfry",
"Batten down the hatches",
"Battle royal",
"Be afraid, be very afraid",
"Be enthralled",
"Be still, my beating heart",
"Bean counter",
"Beast with two backs",
"Beat a hasty retreat",
"Beat around the bush",
"Beauty is only skin deep",
"Beck and call",
"Bed of roses",
"Bee in your bonnet",
"Beef and reef",
"Been there, done that",
"Beer and skittles",
"Bee's knees",
"Beetle browed",
"Beg the question",
"Beggar belief",
"Beggars can't be choosers",
"Behind the eight ball",
"Bell, book and candle",
"Bell the cat",
"Belle of the ball",
"Below the belt",
"Below the salt",
"Bells and whistles",
"Belt and braces",
"Belt up",
"Best bib and tucker",
"Bet your bottom dollar",
"Better half",
"Better late than never",
"Between two stools",
"Beware the Ides of March",
"Beyond belief",
"Beyond our ken",
"Beyond the pale",
"Biblical phrases",
"Big Apple",
"Big cheese",
"Big Easy",
"Big wig",
"Bill Stickers is innocent",
"Billy no mates",
"Binge drinking",
"Birds and the bees",
"Bite the bullet",
"Bite the dust",
"Bitter end",
"Black as Newgate's knocker",
"Black on black",
"Black sheep of the family",
"Blast from the past",
"Blaze a trail",
"Bling bling",
"Blonde bombshell",
"Blood and thunder",
"Blood toil tears and sweat",
"Blood, sweat and tears",
"Bloody minded",
"Blot on the landscape",
"Blow your mind",
"Blow your own trumpet",
"Blown to smithereens",
"Blue blood",
"Blue plate special",
"Bob's your uncle",
"Bode well",
"Bodice ripper",
"Body surfing",
"Bog standard",
"Bolt from the blue",
"Bone dry",
"Bone idle",
"Bone up on",
"Booby prize",
"Booby trap",
"Boogie woogie",
"To big for your boots",
"Booze cruise",
"Born again",
"Boss eyed",
"Bottle out",
"Bottom drawer",
"Bottom up",
"Bought the farm",
"Bowled a maiden over",
"Box and Cox",
"Boxing Day",
"Brand spanking new",
"Brass monkey weather",
"Bread of life",
"Break a leg",
"Break the ice",
"Bricks and clicks",
"Bring home the bacon",
"Broad in the beam",
"Brook no truck with",
"Brown as a berry",
"Browned off",
"Brownie points",
"Brummagem screwdriver",
"Bubble and squeak",
"Buck stops here",
"Buckle down",
"Bugger Bognor!",
"Buggins' turn",
"Bite the Bullet",
"Bums on seats",
"Bun in the oven",
"Bunch of fives",
"Bunny boiler",
"Burning the midnight oil",
"Bury the hatchet",
"Bury your head in the sand",
"Busy as a bee",
"Butter side down",
"By and large",
"By dint of",
"By gum",
"By hook or by crook",
"By the board",
"By the book",
"By the short hairs",
"By the skin of your teeth",
"By your leave",
"Call of the wild",
"Camera cannot lie",
"Canteen culture",
"Carbon copy",
"Carbon footprint",
"Card sharp",
"Carpe diem",
"Carte blanche",
"Cash on the nail",
"Cast the first stone",
"Cat got your tongue?",
"Catch 22",
"Cat's Cradle",
"Caught in a cleft stick",
"Caught by the short hairs",
"Caught red handed",
"Chaise lounge",
"Chalk and cheese",
"Champ at the bit",
"Channel surfing",
"Charley horse",
"Charm offensive",
"Charmed life",
"Cheap at half the price",
"Cherchez la femme",
"Chew the cud",
"Chick flick",
"Chinese whispers",
"Chinless wonder",
"Chip off the old block",
"Chip on your shoulder",
"Chit chat",
"Chock a-block",
"Chop and change",
"Chop chop",
"Chow down",
"Christmas box",
"Christmas card verses",
"Clean breast - make a",
"Clear blue water",
"Cleft stick - In a",
"Cliff hanger",
"Climb on the bandwagon",
"Cloak and dagger",
"Clod hopper",
"Clog up",
"Close, but no cigar",
"Close quarters",
"Cloud cuckoo land",
"Cloud nine",
"Clutch at straws",
"Cock a snook",
"Cock and bull ",
"Coin a phrase",
"Cold as any stone",
"Cold comfort",
"Cold feet",
"Cold shoulder",
"Cold turkey",
"Collywobbles",
"Colour up",
"Come a cropper",
"Come clean",
"Come on down",
"Come up trumps",
"Come what come may",
"Common sense",
"Comparisons are odious",
"Compassion fatigue",
"Complete shambles",
"Cook the books",
"Cookie cutter",
"Cool as a cucumber",
"Cool Britannia",
"Cop an attitude",
"Copper bottomed",
"Cor blimey",
"Cordon bleu",
"Cost an arm and a leg",
"Cotton on to",
"Cotton picking",
"Counting sheep",
"Crack of doom",
"Crapper",
"Crocodile tears",
"Crop up",
"Curate's egg",
"Curiosity killed the cat",
"Curry favour",
"Cut and run",
"Cut of your jib",
"Cut off without a penny",
"Cut the mustard",
"Cut to the chase",
"Cute as a bug's ear",
"Daft as a brush",
"Damp squib",
"Dance attendance on",
"Daniel come to judgement",
"Darby and Joan",
"Dark horse",
"Dark side",
"Darling buds of May",
"Dash to pieces",
"Date rape",
"Davy Jones' locker",
"Daylight robbery",
"Dead as a dodo",
"Dead as a doornail",
"Dead cat bounce",
"Dead ringer",
"Delusions of grandeur",
"Derring do",
"Designer stubble",
"Deus ex machina",
"Devil Incarnate",
"Devil to pay",
"Diamond in the rough",
"Diamond is forever",
"Die hard",
"Die has been cast",
"Different kettle of fish",
"Differently abled",
"Dirt bag",
"Dock your pay",
"Doff your hat",
"Dog days",
"Dog in the manger",
"Dog is a man's best friend",
"Dog's bollocks",
"Dog's breakfast",
"Dog's dinner",
"Dollars to donuts",
"Done a runner",
"Done to a turn",
"Donkey's years",
"Don't die like I did",
"Don't go there",
"Don't have a clue",
"Doom and gloom",
"Double cross",
"Double Dutch",
"Double whammy",
"Down at heel",
"Down in the dumps",
"Down the pan",
"Down the tubes",
"Drag race",
"Draw a blank",
"Draw your horns in",
"Dreams of empire",
"Dressed to the nines",
"Drink like a fish",
"Driving while black",
"Drop dead gorgeous",
"Drop in the bucket",
"Dropping like flies",
"Drummed out of the army",
"Ducks and drakes",
"Dust up",
"Dutch - My old",
"Duvet day",
"Ear candy",
"Ear mark",
"Easy as pie",
"Eat humble pie",
"Eat my hat",
"Economical with the truth",
"Egg on",
"Eighty six",
"Elbow grease",
"Elephant in the room",
"End of story",
"Ends of the earth",
"Et tu, Brute",
"Everybody out",
"Excuse my French",
"Extraordinary rendition",
"Eye candy",
"ear candy",
"Face the music",
"Faff about",
"Faint hearted",
"Fair and square",
"Fair play",
"Fair to middling",
"Fait accompli",
"Fall from grace",
"Fall guy",
"Fall on your sword",
"Fancy free",
"Fancy pants",
"Fashion victim",
"Fast and loose",
"Fast asleep",
"Fathom out",
"Fed up",
"Feeding frenzy",
"Fellow traveller",
"Field day",
"Fifth column",
"Fight the good fight",
"Filthy rich",
"Finagle's Law",
"Fine as frog's hair",
"Fingers and thumbs",
"First water",
"First World",
"Fit as a fiddle",
"Fits and starts",
"Fits to a tee",
"Fixer upper",
"Flash in the pan",
"Flat out",
"Flavor of the month",
"Flesh and blood",
"Flogging a dead horse",
"Flotsam and jetsam",
"Fly in the ointment",
"Fly off the handle",
"Fly on the wall",
"Foam at the mouth",
"Fobbed off",
"Fools' gold",
"Fool's paradise",
"Foot in the door",
"Foot of our stairs",
"For crying out loud",
"For ever and a day",
"For good measure",
"For keeps",
"For the birds",
"For whom the bell tolls",
"Forbidden fruit",
"Foregone conclusion",
"Forewarned is forearmed",
"Forlorn hope",
"Foul play",
"Four by two",
"Freezing temperatures",
"French phrases",
"Friday afternoon car",
"Frog in the throat",
"Frog's hais fine as",
"From sea to shining sea",
"From strength to strength",
"Fruits of your loins",
"Fuddy duddy",
"Full Monty",
"Full of piss and vinegar",
"Full tilt",
"Full to the gunwales",
"Funny farm",
"Fuzzy wuzzy",
"Gad zooks",
"Game is afoot",
"Game is up",
"Game of two halves",
"Gee whiz",
"Generation X",
"Get a word in edgeways",
"Get down to brass tacks",
"Get off on the wrong foot",
"Get off your high horse",
"Get on my wick",
"Get one's dander up",
"Get over it",
"Get the pip",
"Get the sack",
"Get the upper hand",
"Get thee behind me Satan",
"Get underway",
"Get used to it",
"Get your dander up",
"Get your goat",
"Giddy aunt",
"Giddy goat",
"Gild the lily",
"Gilt off the gingerbread",
"Ginned up",
"Ginger up",
"Give a wide berth",
"Give no quarter",
"Give up the ghost",
"Glass ceiling",
"Gloom and doom",
"Go and boil your head",
"Go berserk",
"Go by the board",
"Go by the book",
"Go Dolally",
"Go faster",
"Go for a burton",
"Go haywire",
"Go like the clappers",
"Go off half cocked",
"Go out on a limb",
"Go postal",
"Go pound sand",
"Go the whole hog",
"Go to pot",
"Go to the dogs",
"Go to the mattresses",
"Go whole hog",
"God is dead",
"God rot them",
"Godfrey Daniel",
"Going for a burton",
"Gone for a burton",
"Good as gold",
"Good in parts",
"Good measure - For",
"Good men and true",
"Good riddance",
"Good Samaritan",
"Goody, goody gumdrops",
"Goody two shoes",
"Gordon Bennett",
"Got my mojo working",
"Grand slam",
"Grandfather clock",
"Granny dumping",
"Grasp the nettle",
"Grass up",
"Graveyard shift",
"Greased lightning",
"Great minds think alike",
"Great unwashed",
"Green eyed monster",
"Gregory Peck",
"Grind to a halt",
"Grist to the mill",
"Gry - Words ending in",
"Guinea pig",
"Gung ho",
"Gussied up",
"Guts for garters",
"Hairy eyeball",
"Halcyon days",
"Half cocked",
"Half hearted",
"Half inch",
"Hand over fist",
"Handbags at ten paces",
"Handle with kid gloves",
"Hands down",
"Hanky panky",
"Happy as a clam",
"Happy as a sandboy",
"Happy as Larry",
"Happy clappy",
"Happy slapping",
"Harbinger of doom",
"Hard and fast",
"Hard cases make bad law",
"Hard cheese",
"Hard hearted",
"Hard lines",
"Harp on",
"Hasta la vista, baby",
"Hat trick",
"Have a Captain Cook",
"Have an axe to grind",
"Have an inkling",
"Have no truck with",
"Haven't got a clue",
"Have your guts for garters",
"Head over heels",
"Heads up",
"Hear hear",
"Heart's content",
"Heavens to Betsy",
"Heavens to Murgatroyd",
"Heavy metal",
"Heebie jeebies",
"Hedge your bets",
"Hell in a handbasket",
"Hell or high water",
"Helter skelter",
"Het up",
"Hiding to nothing - On a",
"High and dry",
"High and mighty",
"High five",
"High flyer",
"High horse - get off your",
"High on the hog",
"High time",
"High, wide and handsome",
"Hissy fit",
"History is bunk",
"Hit the ground running",
"Hit the hay",
"Hit the nail on the head",
"Hobson's choice",
"Hobby horse",
"Hocus pocus",
"Hoi polloi",
"Hoist with your own petard",
"Hoity toity",
"Hold your horses",
"Honesty is the best policy",
"Hooray Henry",
"Horse and cart",
"Horse feathers",
"Hot blooded",
"Hot off the press",
"Hot on the heels",
"Household words",
"Houston, we have a problem",
"How are the mighty fallen?",
"How do you do?",
"How now brown cow?",
"Hugger mugger",
"Hung, drawn and quartered",
"Hunky dory",
"Hunt and peck",
"Hush puppies",
"I bear a charmed life",
"I have not slept one wink",
"I haven't got a clue",
"I spy with my little eye",
"I told you is was ill",
"I will swing for you",
"Identity theft",
"If I had my druthers",
"If the cap fits",
"If the shoe fits",
"Ill wind",
"I'm stumped",
"In a cleft stick",
"In a pickle",
"In a pig's eye",
"In a quandary",
"In a trice",
"In like Flynn",
"In limbo",
"In my minds eye",
"In someone's bad books",
"In spades",
"In stitches",
"In the bag",
"In the box seat",
"In the buff",
"In the cart",
"In the catbird seat",
"In the club",
"In the doghouse",
"In the doldrums",
"In the limelight",
"In the nick of time",
"In the offing",
"In the pink",
"In the red",
"In the sticks",
"In the twinkling of an eye",
"In trouble",
"In your face",
"Indian giver",
"Indian summer",
"Infra dig",
"Inside out",
"Iron hoof",
"Is the Pope Catholic?",
"Is the Pope Polish?",
"It is meat and drink to me",
"It's all grist to the mill",
"It's not rocket science",
"It's that man again",
"Ivory tower",
"Jack in the box",
"Jack Palancing",
"Jack the lad",
"Jam tomorrow",
"Jerry built",
"Jimmy Horner",
"Jimmy Riddle",
"Jobs for the boys",
"Join the colours",
"Joined at the hip",
"Johnny on the spot",
"Jot or tittle",
"Jump on the bandwagon",
"Jump the gun",
"Jump the shark",
"Jury is still out",
"Just deserts",
"Just in time",
"Kangaroo court",
"Katy bar the door",
"Keep a wide berth",
"Keen as mustard",
"Keep schtum",
"Keep a stiff upper lip",
"Keep it under your hat",
"Keep the ball rolling",
"Keep up with the Joneses",
"Keep your chin up",
"Keep your hands clean",
"Keep your nose clean",
"Keep your pecker up",
"Keep your powder dry",
"Keepy uppy",
"Kettle of fish",
"Khyber pass",
"Kick the bucket",
"Kick your heels",
"Kickin'live and",
"Kilroy was here",
"Kiss and tell",
"Kiss me Hardy",
"Knee jerk reaction",
"Knick knack",
"Knight in shining armour",
"Knock back",
"Knock into a cocked hat",
"Knock off",
"Knock on wood",
"Know the ropes",
"Know your onions",
"Knuckle down",
"Knuckle under",
"Kowtow to",
"La di da",
"La dolce vita",
"Labour of love",
"Lager frenzy",
"Laid out in lavender",
"La la land",
"Lamb to the slaughter",
"Lame duck",
"Land of nod",
"Lardy dardy",
"Lark about",
"Last but not least",
"Last straw",
"Latin Phrases",
"Laugh like a drain",
"Laughing stock",
"Laurels - rest on one's",
"The law is an ass",
"Lay it on with a trowel",
"Lead pipe cinch",
"Learn the ropes",
"Left in the lurch",
"Less is more",
"Let bygones be bygones",
"Let not poor Nelly starve",
"Let or hindrance",
"Let the cat out of the bag",
"Let them eat cake",
"Let there be light",
"Let your hair down",
"Let's roll",
"Level playing field",
"Lick and a promise",
"Lick into shape",
"Lickety split",
"Lie low",
"Life begins at forty",
"Life of Riley",
"Life's too short",
"Like a moth to a flame",
"Like billy o",
"Like it or lump it",
"Like the clappers",
"Like the Dickens",
"Like two peas in a pod",
"Little bird told me",
"Lions led by donkeys",
"Live long and prosper",
"Living daylights",
"Living on borrowed time",
"Lo and behold",
"Load of cobblers",
"Load of codswallop",
"Loaf of bread",
"Local derby",
"Lock stock and barrel",
"Long in the tooth",
"Look before you leap",
"Loose cannon",
"Loose lips sink ships",
"Lose face",
"Lose your marbles",
"Love is blind",
"Loved up",
"Mad as a hatter",
"Mad as a march hare",
"Magical realism",
"Main chance",
"Make a bee line for",
"Make a clean breast of it",
"Make a pig's ear of",
"Make a virtue of necessity",
"Make haste",
"Make my day",
"Make no bones about",
"Mal de mer",
"Man after my own heart",
"dog is a man's best friend",
"Man's inhumanity to man",
"Many happy returns",
"Mare's nest",
"Marital aid",
"Market forces",
"McCoy real",
"Mea culpa",
"Meat and drink",
"Meat and two veg.",
"Meet your Waterloo",
"Men in suits",
"Mend fences",
"Ménage à trois",
"Merry Christmas",
"Mexican wave",
"Mickey Finn",
"Middle for diddle",
"Middle of the road",
"Might and main",
"Milk of human kindness",
"Minced oaths",
"Mind your Ps and Qs",
"Miss is as good as a mile",
"Moaning Minnie",
"Montezuma's Revenge",
"Monty full",
"Moot point",
"Morbid obesity",
"More bangs for your buck",
"More fool you",
"More light!",
"Morning person",
"Mother country",
"Motley crew",
"Mouth watering",
"Moveable feast",
"Movers and shakers",
"Moving finger writes",
"Moving the goalposts",
"Much Ado about Nothing",
"Much of a muchness",
"Mud - your name is",
"Multitude of sins",
"Mumbo jumbo",
"Mum's the word",
"Murphy's Law",
"Mutt's nuts",
"Mutt and Jeff",
"Mutton dressed as lamb",
"My bad",
"My better half",
"My cup of tea",
"My cup runneth over",
"My giddy aunt",
"My husband and I",
"My mind's eye",
"My old china",
"My old Dutch",
"My salad days",
"My stars and garters",
"Namby pamby",
"Name and shame",
"Name is mud",
"Nasty, brutish and short",
"Nation of shopkeepers",
"Nautical phrases",
"Ne'er do well",
"Needs must",
"Neither here nor there",
"Nest egg",
"Nest of vipers",
"Never knowingly undersold",
"Never never land",
"Never the twain shall meet",
"New kid on the block",
"Nice as ninepence",
"Nice kettle of fish",
"Night owl",
"Nine days' wonder",
"Nip and tuck",
"Nip in the bud",
"Nitty gritty",
"No brainer",
"No dice",
"No holds barred",
"No laughing matter",
"No man is an island",
"No more cakes and ale?",
"No names: no pack drill",
"No quarter given",
"No rest for the wicked",
"No room to swing a cat",
"No truck with",
"No way, Jose",
"Nod land of",
"Norange",
"Nosy parker",
"Not a dicky bird",
"Not my cup of tea",
"Not rocket science",
"Not tonight Josephine",
"Not worth a plugged nickel",
"Not worth the candle",
"Nth degree",
"Nul points",
"O ye, of little faith",
"Odds bodkins",
"Off his own bat",
"Off the record",
"Off with his head",
"Offing - In the",
"Oh, my stars and garters",
"Okey dokey",
"Old as Methuselah",
"Old as the hills",
"Old chestnut",
"Old codger",
"Old hat",
"On a hiding to nothing",
"On a wing and a prayer",
"On Carey Street",
"On cloud nine",
"On queer street",
"On tenterhooks",
"On the ball",
"On the bubble",
"On the button",
"On the dole",
"On the fiddle",
"On the pig's back",
"On the QT",
"On the shoulders of giants",
"On the wagon",
"On the warpath",
"On with the motley",
"On your beam ends",
"On your tod",
"Once in a blue moon",
"One hit wonder",
"One fell swoop",
"One for the road",
"One over the eight",
"One small step for man",
"One stop shop",
"One's heart's content",
"Oops a-daisy",
"Open season",
"Out of sight, out of mind",
"Out of sorts",
"Out of the jaws of death",
"Over a barrel",
"Over the moon",
"Over the top",
"Oxo cube",
"Ps and Qs - Mind your",
"Packed to the gunwales",
"Paddle your own canoe",
"Paint the town red",
"Panic stations",
"Paper tiger",
"Pass the buck",
"P.D.Q. - pretty damn quick",
"Pearls before swine",
"Pears for your heirs",
"Peeping Tom",
"Peg out",
"Pell mell",
"Pester power",
"Peter out",
"Petty cash",
"Physician heal thyself",
"Pick 'n' mix",
"Picture perfect",
"Pies easy as",
"Pie in the sky",
"Piece of cake",
"Piece of piss",
"Piece of the action",
"Pig in a poke",
"Pigeon chested",
"Pig's back - on the",
"Pig's ear",
"Pig and whistle",
"Pigs might fly",
"Pin money",
"Pipe down",
"Pipe dream",
"Piping hot",
"Piss and vinegar - Full of",
"Plain sailing",
"Plates of meat",
"Play by ear",
"Play ducks and drakes",
"Play fast and loose",
"Play it again Sam",
"Play silly buggers",
"Play the giddy goat",
"Play the race card",
"Pleased as Punch",
"Plug ugly",
"Plugged nickel",
"Poetic justice",
"Point and click",
"Politically correct",
"Point blank",
"Point to point",
"Pommy bashing",
"Pond life",
"Pony and trap",
"Pony up",
"Pop goes the weasel",
"Pork pies",
"Take potluck",
"Pound of flesh",
"Power dressing",
"Powers that be",
"Preaching to the choir",
"Press into service",
"Pretty kettle of fish",
"Prick up your ears",
"Prime time",
"Primrose path",
"Proverbs list of",
"Pull in your horns",
"Pull out all the stops",
"Pull up stakes",
"Pull your horns in",
"Punch above one's weight",
"Pure as the driven snow",
"Purple patch",
"Push the boat out",
"Push the envelope",
"Put a damper on",
"Put a sock in it",
"Put a spanner in the works",
"Put on the wooden overcoat",
"Put on your thinking cap",
"Put paid to",
"Put the mockers on",
"Put the wood in the hole",
"Put up your dukes",
"Put your back up",
"Put your best foot forward",
"Put your nose out of joint",
"Pyrric victory",
"Quality time",
"Quarter - Give no",
"Queer as a nine bob note",
"Queer Street",
"Queer the pitch",
"Quick and the dead",
"Quid pro quo",
"Rabbit and pork",
"Rack and ruin",
"Rack your brains",
"Rag, tag and bobtail",
"Raining cats and dogs",
"Raining stair rods",
"Raise Cain",
"Rank and file",
"Raspberry tart",
"Raze to the ground",
"Rat arsed",
"Read between the lines",
"Read the riot act",
"Real McCoy",
"Red handed",
"Red herring",
"Red in tooth and claw",
"Red letter day",
"Red rag to a bull",
"Red sky at night ...",
"Red tape",
"Reduplicated phrases",
"Rest on his laurels",
"Rhyme nor reason",
"Rhyming slang",
"Richard the Third",
"Riding shotgun",
"Riff raff",
"Riley life of",
"Ring down the curtain",
"Ring fencing",
"Ring the changes",
"Rinky dink",
"Rise and shine",
"Road less travelled",
"Road apples",
"Road rage",
"Roasted to a turn",
"Rob Peter to pay Paul",
"Rock and roll",
"It's not rocket science",
"Rose is a rose is a rose",
"Rosie Lea",
"Rough diamond",
"Round Robin",
"Route one",
"Rub of the green",
"Rule of thumb",
"Rum do",
"Rumpy pumpy",
"Run a mile",
"Run amok",
"Run of the mill",
"Run out of steam",
"Run rings around",
"Run the gauntlet",
"Sacred cow",
"Safe pair of hands",
"Safe sex",
"Salad days",
"Salt of the earth",
"San fairy Ann",
"Sandwich short of a picnic",
"Save face",
"Save one's bacon",
"Saved by the bell",
"Savoir faire",
"Say cheese",
"Say goodnight Gracie",
"Scot free",
"Sea change",
"Sealed with a loving kiss",
"Second guess",
"Security blanket",
"See red",
"Seen better days",
"Send packing",
"Senior citizen",
"Sent to Coventry",
"Set one's cap at",
"Set your teeth on edge",
"Sex and shopping",
"Seven year itch",
"Sexton Blake",
"Shebang whole",
"Shaggy dog story",
"Shake a leg",
"Shakers and movers",
"Shanks' mare/shanks' pony",
"Share and share alike",
"Shilly shally",
"Shit for brains",
"Shiver my timbers",
"Shot across the bows",
"Shot in the arm",
"Shot in the dark",
"Shoot through",
"Short shrift",
"Show your mettle",
"Shut your cake hole",
"Sick puppy",
"Sight for sore eyes",
"Silly Billy",
"Silly season",
"Silence is golden",
"Silver bullet",
"Sixes and sevens",
"Skeleton in the closet",
"Skid row",
"Skin and blister",
"Sleep like a top",
"Sleep on a clothesline",
"Sleep tight",
"Sloane Ranger",
"Slush fund",
"Smart casual",
"Smoke and mirrors",
"Snug as a bug in a rug",
"So sue me",
"Soap dodger",
"Sod's Law",
"Sold down the river",
"Son of a gun",
"Sorry sight",
"Sound bite",
"Sound out",
"Sour grapes",
"Space, the final frontier",
"Speak of the Devil",
"Special relationship",
"Spelling bee",
"Spend a penny",
"Spick and span",
"Spill the beans",
"Spin doctor",
"Spitting feathers",
"Spitting image",
"Spring forward, fall back",
"Spruce up",
"Square meal",
"Squeaky bum time",
"Stand and deliver",
"Stand up guy",
"Stars and garters",
"Start from scratch",
"Steal a march",
"Steal my thunder",
"Stick in the mud",
"Sticky wicket",
"Stiffen the sinews",
"Stinking rich",
"Stone the crows",
"Stone's throw",
"Stony hearted",
"Stool pigeon",
"Storm in a teacup",
"Straight as a die",
"Strain at the leash",
"Strait laced",
"Strait and narrow",
"Stranger danger",
"Stuff and nonsense",
"Stump up",
"Such is life",
"Surf and turf",
"Surfing the Net",
"surfing the Internet",
"surfing the Web",
"Survival of the fittest",
"Suspension of disbelief",
"Swan song",
"Take the Mickey",
"Take umbrage",
"Talk to the hand",
"Tall story",
"Tea leaf",
"Tempest in a teapot",
"Thick and thin",
"Thinking cap",
"Third degree",
"Thorn in the flesh",
"Thou shalt not kill",
"Throw in the towel",
"Thumbs up",
"Ticked off",
"Tickle the ivories",
"Tickled pink",
"Tide over",
"Tie the knot",
"To beggar belief",
"To boot",
"Toast of the town",
"Toe the line",
"Toe curling",
"Toffee nosed",
"Tongue in cheek",
"Toodle oo",
"Top dog",
"Top drawer",
"Top notch",
"Topsy turvy",
"Total shambles",
"Touch wood",
"Touchy feely",
"Tout de suite",
"Tower of strength",
"Train surfing",
"Trick or treat",
"Trouble and strife",
"True blue",
"Tuckered out",
"Turn of phrase",
"Turn the tables",
"peas in a pod",
"Under the thumb",
"apples and pears",
"Up the duff",
"Up the pole",
"Up to snuff",
"Upper crust",
"Upper hand",
"Up in arms",
"Upside down",
"Urban myth",
"Usual suspects",
"Veg out",
"Vice versa",
"Vicious circle",
"Walk free",
"Walk the plank",
"Warts and all",
"Wax lyrical",
"Wax poetic",
"Weakest link",
"Weasel words",
"Wee wee",
"Well heeled",
"Well read",
"When pigs fly",
"Whet your appetite",
"Whistle and flute",
"White bread",
"Whipper snapper",
"Whipping boy",
"White elephant",
"Whole hearted",
"Whole nine",
"Willy nilly",
"Worse for wear",
"Young turk",
"Your money or your life",
"Zero tolerance",
"Zig zag"
]
