module.exports =
[ { phrase: 'Bang for your buck', words: [ 'Bang', 'buck' ] },
  { phrase: 'bird in the hand', words: [ 'bird', 'hand' ] },
  { phrase: 'bunch of fives', words: [ 'bunch', 'fives' ] },
  { phrase: 'diamond in the rough',
    words: [ 'diamond', 'rough' ] },
  { phrase: 'drop in the bucket', words: [ 'drop', 'bucket' ] },
  { phrase: 'drop in the ocean', words: [ 'drop', 'ocean' ] },
  { phrase: 'fish out of water', words: [ 'fish', 'water' ] },
  { phrase: 'fly in the ointment', words: [ 'fly', 'ointment' ] },
  { phrase: 'fool\'s paradise', words: [ 'fool\'s', 'paradise' ] },
  { phrase: 'foot in the door', words: [ 'foot', 'door' ] },
  { phrase: 'foregone conclusion',
    words: [ 'foregone', 'conclusion' ] },
  { phrase: 'load of codswallop',
    words: [ 'load', 'codswallop' ] },
  { phrase: 'nation of shopkeepers',
    words: [ 'nation', 'shopkeepers' ] },
  { phrase: 'nest of vipers', words: [ 'nest', 'vipers' ] },
  { phrase: 'piece of the action', words: [ 'piece', 'action' ] },
  { phrase: 'pig in a poke', words: [ 'pig', 'poke' ] },
  { phrase: 'sea change', words: [ 'sea', 'change' ] },
  { phrase: 'skeleton in the closet',
    words: [ 'skeleton', 'closet' ] },
  { phrase: 'shot in the arm', words: [ 'shot', 'arm' ] },
  { phrase: 'stone\'s throw', words: [ 'stone\'s', 'throw' ] },
  { phrase: 'tinker\'s damn', words: [ 'tinker\'s', 'damn' ] },
  { phrase: 'word in edgeways', words: [ 'word', 'edgeways' ] },
  { phrase: 'Ace in the hole', words: [ 'Ace', 'hole' ] },
  { phrase: 'Achilles\' heel', words: [ 'Achilles\'', 'heel' ] },
  { phrase: 'Acid test', words: [ 'Acid', 'test' ] },
  { phrase: 'Act of God', words: [ 'Act', 'God' ] },
  { phrase: 'Action man', words: [ 'Action', 'man' ] },
  { phrase: 'Adam\'s ale', words: [ 'Adam\'s', 'ale' ] },
  { phrase: 'Aga saga', words: [ 'Aga', 'saga' ] },
  { phrase: 'Age before beauty', words: [ 'Age', 'beauty' ] },
  { phrase: 'Agree to disagree', words: [ 'Agree', 'disagree' ] },
  { phrase: 'Aid and abet', words: [ 'Aid', 'abet' ] },
  { phrase: 'Aide mémoire', words: [ 'Aide', 'mémoire' ] },
  { phrase: 'Air kiss', words: [ 'Air', 'kiss' ] },
  { phrase: 'Air quotes', words: [ 'Air', 'quotes' ] },
  { phrase: 'Al fresco', words: [ 'Al', 'fresco' ] },
  { phrase: 'two peas in a pod', words: [ 'peas', 'pod' ] },
  { phrase: 'Alive and kicking', words: [ 'Alive', 'kicking' ] },
  { phrase: 'All fingers and thumbs',
    words: [ 'fingers', 'thumbs' ] },
  { phrase: 'All intents and purposes',
    words: [ 'intents', 'purposes' ] },
  { phrase: 'All present and correct',
    words: [ 'present', 'correct' ] },
  { phrase: 'All singing, all dancing',
    words: [ 'singing,', 'dancing' ] },
  { phrase: 'Alter ego', words: [ 'Alter', 'ego' ] },
  { phrase: 'Amber nectar', words: [ 'Amber', 'nectar' ] },
  { phrase: 'An arm and a leg', words: [ 'arm', 'leg' ] },
  { phrase: 'An Oxford scholar', words: [ 'Oxford', 'scholar' ] },
  { phrase: 'Anchors aweigh', words: [ 'Anchors', 'aweigh' ] },
  { phrase: 'Ankle biter', words: [ 'Ankle', 'biter' ] },
  { phrase: 'April fool', words: [ 'April', 'fool' ] },
  { phrase: 'Arm candy', words: [ 'Arm', 'candy' ] },
  { phrase: 'Arms akimbo', words: [ 'Arms', 'akimbo' ] },
  { phrase: 'Arty farty', words: [ 'Arty', 'farty' ] },
  { phrase: 'At one fell swoop', words: [ 'fell', 'swoop' ] },
  { phrase: 'At sixes and sevens', words: [ 'sixes', 'sevens' ] },
  { phrase: 'Baby blues', words: [ 'Baby', 'blues' ] },
  { phrase: 'Baby boomer', words: [ 'Baby', 'boomer' ] },
  { phrase: 'Baby father', words: [ 'Baby', 'father' ] },
  { phrase: 'Back seat driver', words: [ 'seat', 'driver' ] },
  { phrase: 'Backroom boy', words: [ 'Backroom', 'boy' ] },
  { phrase: 'Bad books', words: [ 'Bad', 'books' ] },
  { phrase: 'Bad egg', words: [ 'Bad', 'egg' ] },
  { phrase: 'Badger to death', words: [ 'Badger', 'death' ] },
  { phrase: 'Bag and baggage', words: [ 'Bag', 'baggage' ] },
  { phrase: 'Baker\'s dozen', words: [ 'Baker\'s', 'dozen' ] },
  { phrase: 'Balance of power', words: [ 'Balance', 'power' ] },
  { phrase: 'Balance of trade', words: [ 'Balance', 'trade' ] },
  { phrase: 'Bald as a coot', words: [ 'Bald', 'coot' ] },
  { phrase: 'Bale out/bail out', words: [ 'Bale', 'out/bail' ] },
  { phrase: 'Ball and chain', words: [ 'Ball', 'chain' ] },
  { phrase: 'Bandy words', words: [ 'Bandy', 'words' ] },
  { phrase: 'Bane of your life', words: [ 'Bane', 'life' ] },
  { phrase: 'Baptism of fire', words: [ 'Baptism', 'fire' ] },
  { phrase: 'Barking mad', words: [ 'Barking', 'mad' ] },
  { phrase: 'Basket case', words: [ 'Basket', 'case' ] },
  { phrase: 'Bated breath', words: [ 'Bated', 'breath' ] },
  { phrase: 'Bats in the belfry', words: [ 'Bats', 'belfry' ] },
  { phrase: 'Batten down the hatches',
    words: [ 'Batten', 'hatches' ] },
  { phrase: 'Battle royal', words: [ 'Battle', 'royal' ] },
  { phrase: 'Be afraid, be very afraid',
    words: [ 'afraid,', 'afraid' ] },
  { phrase: 'Bean counter', words: [ 'Bean', 'counter' ] },
  { phrase: 'Beast with two backs', words: [ 'Beast', 'backs' ] },
  { phrase: 'Beat around the bush', words: [ 'Beat', 'bush' ] },
  { phrase: 'Beck and call', words: [ 'Beck', 'call' ] },
  { phrase: 'Bed of roses', words: [ 'Bed', 'roses' ] },
  { phrase: 'Bee in your bonnet', words: [ 'Bee', 'bonnet' ] },
  { phrase: 'Beef and reef', words: [ 'Beef', 'reef' ] },
  { phrase: 'Beer and skittles', words: [ 'Beer', 'skittles' ] },
  { phrase: 'Bee\'s knees', words: [ 'Bee\'s', 'knees' ] },
  { phrase: 'Beetle browed', words: [ 'Beetle', 'browed' ] },
  { phrase: 'Beg the question', words: [ 'Beg', 'question' ] },
  { phrase: 'Beggar belief', words: [ 'Beggar', 'belief' ] },
  { phrase: 'Bell the cat', words: [ 'Bell', 'cat' ] },
  { phrase: 'Belle of the ball', words: [ 'Belle', 'ball' ] },
  { phrase: 'Bells and whistles', words: [ 'Bells', 'whistles' ] },
  { phrase: 'Belt and braces', words: [ 'Belt', 'braces' ] },
  { phrase: 'Best bib and tucker', words: [ 'bib', 'tucker' ] },
  { phrase: 'Biblical phrases', words: [ 'Biblical', 'phrases' ] },
  { phrase: 'Big Apple', words: [ 'Big', 'Apple' ] },
  { phrase: 'Big cheese', words: [ 'Big', 'cheese' ] },
  { phrase: 'Big Easy', words: [ 'Big', 'Easy' ] },
  { phrase: 'Big wig', words: [ 'Big', 'wig' ] },
  { phrase: 'Billy no mates', words: [ 'Billy', 'mates' ] },
  { phrase: 'Binge drinking', words: [ 'Binge', 'drinking' ] },
  { phrase: 'Birds and the bees', words: [ 'Birds', 'bees' ] },
  { phrase: 'Bite the bullet', words: [ 'Bite', 'bullet' ] },
  { phrase: 'Bite the dust', words: [ 'Bite', 'dust' ] },
  { phrase: 'Black on black', words: [ 'Black', 'black' ] },
  { phrase: 'Blaze a trail', words: [ 'Blaze', 'trail' ] },
  { phrase: 'Bling bling', words: [ 'Bling', 'bling' ] },
  { phrase: 'Blonde bombshell', words: [ 'Blonde', 'bombshell' ] },
  { phrase: 'Blood and thunder', words: [ 'Blood', 'thunder' ] },
  { phrase: 'Bloody minded', words: [ 'Bloody', 'minded' ] },
  { phrase: 'Blot on the landscape',
    words: [ 'Blot', 'landscape' ] },
  { phrase: 'Blow your mind', words: [ 'Blow', 'mind' ] },
  { phrase: 'Blow your own trumpet',
    words: [ 'Blow', 'trumpet' ] },
  { phrase: 'Blown to smithereens',
    words: [ 'Blown', 'smithereens' ] },
  { phrase: 'Blue blood', words: [ 'Blue', 'blood' ] },
  { phrase: 'Bob\'s your uncle', words: [ 'Bob\'s', 'uncle' ] },
  { phrase: 'Bodice ripper', words: [ 'Bodice', 'ripper' ] },
  { phrase: 'Body surfing', words: [ 'Body', 'surfing' ] },
  { phrase: 'Bog standard', words: [ 'Bog', 'standard' ] },
  { phrase: 'Bolt from the blue', words: [ 'Bolt', 'blue' ] },
  { phrase: 'Bone dry', words: [ 'Bone', 'dry' ] },
  { phrase: 'Bone idle', words: [ 'Bone', 'idle' ] },
  { phrase: 'Booby prize', words: [ 'Booby', 'prize' ] },
  { phrase: 'Booby trap', words: [ 'Booby', 'trap' ] },
  { phrase: 'Boogie woogie', words: [ 'Boogie', 'woogie' ] },
  { phrase: 'To big for your boots', words: [ 'big', 'boots' ] },
  { phrase: 'Booze cruise', words: [ 'Booze', 'cruise' ] },
  { phrase: 'Boss eyed', words: [ 'Boss', 'eyed' ] },
  { phrase: 'Bottom drawer', words: [ 'Bottom', 'drawer' ] },
  { phrase: 'Bought the farm', words: [ 'Bought', 'farm' ] },
  { phrase: 'Bowled a maiden over',
    words: [ 'Bowled', 'maiden' ] },
  { phrase: 'Box and Cox', words: [ 'Box', 'Cox' ] },
  { phrase: 'Boxing Day', words: [ 'Boxing', 'Day' ] },
  { phrase: 'Brand spanking new', words: [ 'Brand', 'spanking' ] },
  { phrase: 'Bread of life', words: [ 'Bread', 'life' ] },
  { phrase: 'Break a leg', words: [ 'Break', 'leg' ] },
  { phrase: 'Break the ice', words: [ 'Break', 'ice' ] },
  { phrase: 'Bricks and clicks', words: [ 'Bricks', 'clicks' ] },
  { phrase: 'Broad in the beam', words: [ 'Broad', 'beam' ] },
  { phrase: 'Brook no truck with', words: [ 'Brook', 'truck' ] },
  { phrase: 'Brown as a berry', words: [ 'Brown', 'berry' ] },
  { phrase: 'Brownie points', words: [ 'Brownie', 'points' ] },
  { phrase: 'Brummagem screwdriver',
    words: [ 'Brummagem', 'screwdriver' ] },
  { phrase: 'Bubble and squeak', words: [ 'Bubble', 'squeak' ] },
  { phrase: 'Buck stops here', words: [ 'Buck', 'stops' ] },
  { phrase: 'Bugger Bognor!', words: [ 'Bugger', 'Bognor!' ] },
  { phrase: 'Buggins\' turn', words: [ 'Buggins\'', 'turn' ] },
  { phrase: 'Bite the Bullet', words: [ 'Bite', 'Bullet' ] },
  { phrase: 'Bums on seats', words: [ 'Bums', 'seats' ] },
  { phrase: 'Bun in the oven', words: [ 'Bun', 'oven' ] },
  { phrase: 'Bunch of fives', words: [ 'Bunch', 'fives' ] },
  { phrase: 'Bunny boiler', words: [ 'Bunny', 'boiler' ] },
  { phrase: 'Bury the hatchet', words: [ 'Bury', 'hatchet' ] },
  { phrase: 'Busy as a bee', words: [ 'Busy', 'bee' ] },
  { phrase: 'Butter side down', words: [ 'Butter', 'side' ] },
  { phrase: 'By hook or by crook', words: [ 'hook', 'crook' ] },
  { phrase: 'By the short hairs', words: [ 'short', 'hairs' ] },
  { phrase: 'By the skin of your teeth',
    words: [ 'skin', 'teeth' ] },
  { phrase: 'Call of the wild', words: [ 'Call', 'wild' ] },
  { phrase: 'Camera cannot lie', words: [ 'Camera', 'lie' ] },
  { phrase: 'Canteen culture', words: [ 'Canteen', 'culture' ] },
  { phrase: 'Carbon copy', words: [ 'Carbon', 'copy' ] },
  { phrase: 'Carbon footprint', words: [ 'Carbon', 'footprint' ] },
  { phrase: 'Card sharp', words: [ 'Card', 'sharp' ] },
  { phrase: 'Carpe diem', words: [ 'Carpe', 'diem' ] },
  { phrase: 'Carte blanche', words: [ 'Carte', 'blanche' ] },
  { phrase: 'Cash on the nail', words: [ 'Cash', 'nail' ] },
  { phrase: 'Cast the first stone', words: [ 'Cast', 'stone' ] },
  { phrase: 'Cat got your tongue?', words: [ 'Cat', 'tongue?' ] },
  { phrase: 'Catch 22', words: [ 'Catch', '22' ] },
  { phrase: 'Cat\'s Cradle', words: [ 'Cat\'s', 'Cradle' ] },
  { phrase: 'Chaise lounge', words: [ 'Chaise', 'lounge' ] },
  { phrase: 'Chalk and cheese', words: [ 'Chalk', 'cheese' ] },
  { phrase: 'Champ at the bit', words: [ 'Champ', 'bit' ] },
  { phrase: 'Channel surfing', words: [ 'Channel', 'surfing' ] },
  { phrase: 'Charley horse', words: [ 'Charley', 'horse' ] },
  { phrase: 'Charm offensive', words: [ 'Charm', 'offensive' ] },
  { phrase: 'Charmed life', words: [ 'Charmed', 'life' ] },
  { phrase: 'Cheap at half the price',
    words: [ 'Cheap', 'price' ] },
  { phrase: 'Chew the cud', words: [ 'Chew', 'cud' ] },
  { phrase: 'Chick flick', words: [ 'Chick', 'flick' ] },
  { phrase: 'Chinese whispers', words: [ 'Chinese', 'whispers' ] },
  { phrase: 'Chip off the old block', words: [ 'Chip', 'block' ] },
  { phrase: 'Chip on your shoulder',
    words: [ 'Chip', 'shoulder' ] },
  { phrase: 'Chit chat', words: [ 'Chit', 'chat' ] },
  { phrase: 'Chock a-block', words: [ 'Chock', 'a-block' ] },
  { phrase: 'Chop and change', words: [ 'Chop', 'change' ] },
  { phrase: 'Chop chop', words: [ 'Chop', 'chop' ] },
  { phrase: 'Christmas box', words: [ 'Christmas', 'box' ] },
  { phrase: 'Cliff hanger', words: [ 'Cliff', 'hanger' ] },
  { phrase: 'Climb on the bandwagon',
    words: [ 'Climb', 'bandwagon' ] },
  { phrase: 'Cloak and dagger', words: [ 'Cloak', 'dagger' ] },
  { phrase: 'Clod hopper', words: [ 'Clod', 'hopper' ] },
  { phrase: 'Close, but no cigar', words: [ 'Close,', 'cigar' ] },
  { phrase: 'Close quarters', words: [ 'Close', 'quarters' ] },
  { phrase: 'Clutch at straws', words: [ 'Clutch', 'straws' ] },
  { phrase: 'Cock a snook', words: [ 'Cock', 'snook' ] },
  { phrase: 'Coin a phrase', words: [ 'Coin', 'phrase' ] },
  { phrase: 'Cold as any stone', words: [ 'Cold', 'stone' ] },
  { phrase: 'Cold comfort', words: [ 'Cold', 'comfort' ] },
  { phrase: 'Cold feet', words: [ 'Cold', 'feet' ] },
  { phrase: 'Cold shoulder', words: [ 'Cold', 'shoulder' ] },
  { phrase: 'Cold turkey', words: [ 'Cold', 'turkey' ] },
  { phrase: 'Common sense', words: [ 'Common', 'sense' ] },
  { phrase: 'Comparisons are odious',
    words: [ 'Comparisons', 'odious' ] },
  { phrase: 'Compassion fatigue',
    words: [ 'Compassion', 'fatigue' ] },
  { phrase: 'Complete shambles',
    words: [ 'Complete', 'shambles' ] },
  { phrase: 'Cook the books', words: [ 'Cook', 'books' ] },
  { phrase: 'Cookie cutter', words: [ 'Cookie', 'cutter' ] },
  { phrase: 'Cool as a cucumber', words: [ 'Cool', 'cucumber' ] },
  { phrase: 'Cool Britannia', words: [ 'Cool', 'Britannia' ] },
  { phrase: 'Cop an attitude', words: [ 'Cop', 'attitude' ] },
  { phrase: 'Copper bottomed', words: [ 'Copper', 'bottomed' ] },
  { phrase: 'Cor blimey', words: [ 'Cor', 'blimey' ] },
  { phrase: 'Cordon bleu', words: [ 'Cordon', 'bleu' ] },
  { phrase: 'Cotton picking', words: [ 'Cotton', 'picking' ] },
  { phrase: 'Counting sheep', words: [ 'Counting', 'sheep' ] },
  { phrase: 'Crack of doom', words: [ 'Crack', 'doom' ] },
  { phrase: 'Crocodile tears', words: [ 'Crocodile', 'tears' ] },
  { phrase: 'Curate\'s egg', words: [ 'Curate\'s', 'egg' ] },
  { phrase: 'Curry favour', words: [ 'Curry', 'favour' ] },
  { phrase: 'Cut and run', words: [ 'Cut', 'run' ] },
  { phrase: 'Cut of your jib', words: [ 'Cut', 'jib' ] },
  { phrase: 'Cut off without a penny', words: [ 'Cut', 'penny' ] },
  { phrase: 'Cut the mustard', words: [ 'Cut', 'mustard' ] },
  { phrase: 'Cut to the chase', words: [ 'Cut', 'chase' ] },
  { phrase: 'Daft as a brush', words: [ 'Daft', 'brush' ] },
  { phrase: 'Damp squib', words: [ 'Damp', 'squib' ] },
  { phrase: 'Dance attendance on',
    words: [ 'Dance', 'attendance' ] },
  { phrase: 'Daniel come to judgement',
    words: [ 'Daniel', 'judgement' ] },
  { phrase: 'Darby and Joan', words: [ 'Darby', 'Joan' ] },
  { phrase: 'Dark horse', words: [ 'Dark', 'horse' ] },
  { phrase: 'Dark side', words: [ 'Dark', 'side' ] },
  { phrase: 'Darling buds of May', words: [ 'Darling', 'buds' ] },
  { phrase: 'Dash to pieces', words: [ 'Dash', 'pieces' ] },
  { phrase: 'Date rape', words: [ 'Date', 'rape' ] },
  { phrase: 'Daylight robbery', words: [ 'Daylight', 'robbery' ] },
  { phrase: 'Dead as a dodo', words: [ 'Dead', 'dodo' ] },
  { phrase: 'Dead as a doornail', words: [ 'Dead', 'doornail' ] },
  { phrase: 'Dead ringer', words: [ 'Dead', 'ringer' ] },
  { phrase: 'Delusions of grandeur',
    words: [ 'Delusions', 'grandeur' ] },
  { phrase: 'Designer stubble', words: [ 'Designer', 'stubble' ] },
  { phrase: 'Deus ex machina', words: [ 'Deus', 'machina' ] },
  { phrase: 'Devil Incarnate', words: [ 'Devil', 'Incarnate' ] },
  { phrase: 'Devil to pay', words: [ 'Devil', 'pay' ] },
  { phrase: 'Diamond in the rough',
    words: [ 'Diamond', 'rough' ] },
  { phrase: 'Die hard', words: [ 'Die', 'hard' ] },
  { phrase: 'Die has been cast', words: [ 'Die', 'cast' ] },
  { phrase: 'Different kettle of fish',
    words: [ 'kettle', 'fish' ] },
  { phrase: 'Differently abled',
    words: [ 'Differently', 'abled' ] },
  { phrase: 'Dirt bag', words: [ 'Dirt', 'bag' ] },
  { phrase: 'Dock your pay', words: [ 'Dock', 'pay' ] },
  { phrase: 'Doff your hat', words: [ 'Doff', 'hat' ] },
  { phrase: 'Dog days', words: [ 'Dog', 'days' ] },
  { phrase: 'Dog in the manger', words: [ 'Dog', 'manger' ] },
  { phrase: 'Dog\'s bollocks', words: [ 'Dog\'s', 'bollocks' ] },
  { phrase: 'Dog\'s breakfast', words: [ 'Dog\'s', 'breakfast' ] },
  { phrase: 'Dog\'s dinner', words: [ 'Dog\'s', 'dinner' ] },
  { phrase: 'Dollars to donuts', words: [ 'Dollars', 'donuts' ] },
  { phrase: 'Donkey\'s years', words: [ 'Donkey\'s', 'years' ] },
  { phrase: 'Don\'t die like I did', words: [ 'Don\'t', 'die' ] },
  { phrase: 'Don\'t have a clue', words: [ 'Don\'t', 'clue' ] },
  { phrase: 'Doom and gloom', words: [ 'Doom', 'gloom' ] },
  { phrase: 'Double cross', words: [ 'Double', 'cross' ] },
  { phrase: 'Double Dutch', words: [ 'Double', 'Dutch' ] },
  { phrase: 'Double whammy', words: [ 'Double', 'whammy' ] },
  { phrase: 'Drag race', words: [ 'Drag', 'race' ] },
  { phrase: 'Draw a blank', words: [ 'Draw', 'blank' ] },
  { phrase: 'Draw your horns in', words: [ 'Draw', 'horns' ] },
  { phrase: 'Dreams of empire', words: [ 'Dreams', 'empire' ] },
  { phrase: 'Dressed to the nines',
    words: [ 'Dressed', 'nines' ] },
  { phrase: 'Drink like a fish', words: [ 'Drink', 'fish' ] },
  { phrase: 'Driving while black', words: [ 'Driving', 'black' ] },
  { phrase: 'Drop in the bucket', words: [ 'Drop', 'bucket' ] },
  { phrase: 'Dropping like flies',
    words: [ 'Dropping', 'flies' ] },
  { phrase: 'Drummed out of the army',
    words: [ 'Drummed', 'army' ] },
  { phrase: 'Ducks and drakes', words: [ 'Ducks', 'drakes' ] },
  { phrase: 'Dutch - My old', words: [ 'Dutch', '-' ] },
  { phrase: 'Duvet day', words: [ 'Duvet', 'day' ] },
  { phrase: 'Ear candy', words: [ 'Ear', 'candy' ] },
  { phrase: 'Ear mark', words: [ 'Ear', 'mark' ] },
  { phrase: 'Easy as pie', words: [ 'Easy', 'pie' ] },
  { phrase: 'Eat my hat', words: [ 'Eat', 'hat' ] },
  { phrase: 'Economical with the truth',
    words: [ 'Economical', 'truth' ] },
  { phrase: 'Elbow grease', words: [ 'Elbow', 'grease' ] },
  { phrase: 'Elephant in the room',
    words: [ 'Elephant', 'room' ] },
  { phrase: 'Ends of the earth', words: [ 'Ends', 'earth' ] },
  { phrase: 'Et tu, Brute', words: [ 'tu,', 'Brute' ] },
  { phrase: 'Excuse my French', words: [ 'Excuse', 'French' ] },
  { phrase: 'Extraordinary rendition',
    words: [ 'Extraordinary', 'rendition' ] },
  { phrase: 'Eye candy', words: [ 'Eye', 'candy' ] },
  { phrase: 'ear candy', words: [ 'ear', 'candy' ] },
  { phrase: 'Face the music', words: [ 'Face', 'music' ] },
  { phrase: 'Faint hearted', words: [ 'Faint', 'hearted' ] },
  { phrase: 'Fair and square', words: [ 'Fair', 'square' ] },
  { phrase: 'Fair play', words: [ 'Fair', 'play' ] },
  { phrase: 'Fair to middling', words: [ 'Fair', 'middling' ] },
  { phrase: 'Fait accompli', words: [ 'Fait', 'accompli' ] },
  { phrase: 'Fall from grace', words: [ 'Fall', 'grace' ] },
  { phrase: 'Fall guy', words: [ 'Fall', 'guy' ] },
  { phrase: 'Fall on your sword', words: [ 'Fall', 'sword' ] },
  { phrase: 'Fancy free', words: [ 'Fancy', 'free' ] },
  { phrase: 'Fancy pants', words: [ 'Fancy', 'pants' ] },
  { phrase: 'Fashion victim', words: [ 'Fashion', 'victim' ] },
  { phrase: 'Fast and loose', words: [ 'Fast', 'loose' ] },
  { phrase: 'Fast asleep', words: [ 'Fast', 'asleep' ] },
  { phrase: 'Feeding frenzy', words: [ 'Feeding', 'frenzy' ] },
  { phrase: 'Fellow traveller', words: [ 'Fellow', 'traveller' ] },
  { phrase: 'Field day', words: [ 'Field', 'day' ] },
  { phrase: 'Filthy rich', words: [ 'Filthy', 'rich' ] },
  { phrase: 'Finagle\'s Law', words: [ 'Finagle\'s', 'Law' ] },
  { phrase: 'Fingers and thumbs', words: [ 'Fingers', 'thumbs' ] },
  { phrase: 'Fit as a fiddle', words: [ 'Fit', 'fiddle' ] },
  { phrase: 'Fits and starts', words: [ 'Fits', 'starts' ] },
  { phrase: 'Fits to a tee', words: [ 'Fits', 'tee' ] },
  { phrase: 'Fixer upper', words: [ 'Fixer', 'upper' ] },
  { phrase: 'Flash in the pan', words: [ 'Flash', 'pan' ] },
  { phrase: 'Flavor of the month', words: [ 'Flavor', 'month' ] },
  { phrase: 'Flesh and blood', words: [ 'Flesh', 'blood' ] },
  { phrase: 'Flotsam and jetsam', words: [ 'Flotsam', 'jetsam' ] },
  { phrase: 'Fly in the ointment', words: [ 'Fly', 'ointment' ] },
  { phrase: 'Fly off the handle', words: [ 'Fly', 'handle' ] },
  { phrase: 'Fly on the wall', words: [ 'Fly', 'wall' ] },
  { phrase: 'Foam at the mouth', words: [ 'Foam', 'mouth' ] },
  { phrase: 'Fools\' gold', words: [ 'Fools\'', 'gold' ] },
  { phrase: 'Fool\'s paradise', words: [ 'Fool\'s', 'paradise' ] },
  { phrase: 'Foot in the door', words: [ 'Foot', 'door' ] },
  { phrase: 'Foot of our stairs', words: [ 'Foot', 'stairs' ] },
  { phrase: 'For crying out loud', words: [ 'crying', 'loud' ] },
  { phrase: 'For good measure', words: [ 'good', 'measure' ] },
  { phrase: 'For whom the bell tolls',
    words: [ 'bell', 'tolls' ] },
  { phrase: 'Forbidden fruit', words: [ 'Forbidden', 'fruit' ] },
  { phrase: 'Foregone conclusion',
    words: [ 'Foregone', 'conclusion' ] },
  { phrase: 'Forewarned is forearmed',
    words: [ 'Forewarned', 'forearmed' ] },
  { phrase: 'Forlorn hope', words: [ 'Forlorn', 'hope' ] },
  { phrase: 'Foul play', words: [ 'Foul', 'play' ] },
  { phrase: 'Freezing temperatures',
    words: [ 'Freezing', 'temperatures' ] },
  { phrase: 'French phrases', words: [ 'French', 'phrases' ] },
  { phrase: 'Frog in the throat', words: [ 'Frog', 'throat' ] },
  { phrase: 'From strength to strength',
    words: [ 'strength', 'strength' ] },
  { phrase: 'Fruits of your loins', words: [ 'Fruits', 'loins' ] },
  { phrase: 'Fuddy duddy', words: [ 'Fuddy', 'duddy' ] },
  { phrase: 'Full Monty', words: [ 'Full', 'Monty' ] },
  { phrase: 'Full tilt', words: [ 'Full', 'tilt' ] },
  { phrase: 'Full to the gunwales',
    words: [ 'Full', 'gunwales' ] },
  { phrase: 'Funny farm', words: [ 'Funny', 'farm' ] },
  { phrase: 'Fuzzy wuzzy', words: [ 'Fuzzy', 'wuzzy' ] },
  { phrase: 'Gad zooks', words: [ 'Gad', 'zooks' ] },
  { phrase: 'Game is afoot', words: [ 'Game', 'afoot' ] },
  { phrase: 'Game of two halves', words: [ 'Game', 'halves' ] },
  { phrase: 'Gee whiz', words: [ 'Gee', 'whiz' ] },
  { phrase: 'Get a word in edgeways',
    words: [ 'word', 'edgeways' ] },
  { phrase: 'Get down to brass tacks',
    words: [ 'brass', 'tacks' ] },
  { phrase: 'Get off on the wrong foot',
    words: [ 'wrong', 'foot' ] },
  { phrase: 'Get off your high horse',
    words: [ 'high', 'horse' ] },
  { phrase: 'Get one\'s dander up',
    words: [ 'one\'s', 'dander' ] },
  { phrase: 'Get the upper hand', words: [ 'upper', 'hand' ] },
  { phrase: 'Get thee behind me Satan',
    words: [ 'thee', 'Satan' ] },
  { phrase: 'Giddy aunt', words: [ 'Giddy', 'aunt' ] },
  { phrase: 'Giddy goat', words: [ 'Giddy', 'goat' ] },
  { phrase: 'Gild the lily', words: [ 'Gild', 'lily' ] },
  { phrase: 'Gilt off the gingerbread',
    words: [ 'Gilt', 'gingerbread' ] },
  { phrase: 'Give no quarter', words: [ 'Give', 'quarter' ] },
  { phrase: 'Give up the ghost', words: [ 'Give', 'ghost' ] },
  { phrase: 'Glass ceiling', words: [ 'Glass', 'ceiling' ] },
  { phrase: 'Gloom and doom', words: [ 'Gloom', 'doom' ] },
  { phrase: 'Go and boil your head', words: [ 'boil', 'head' ] },
  { phrase: 'Go pound sand', words: [ 'pound', 'sand' ] },
  { phrase: 'God is dead', words: [ 'God', 'dead' ] },
  { phrase: 'God rot them', words: [ 'God', 'rot' ] },
  { phrase: 'Godfrey Daniel', words: [ 'Godfrey', 'Daniel' ] },
  { phrase: 'Good as gold', words: [ 'Good', 'gold' ] },
  { phrase: 'Good in parts', words: [ 'Good', 'parts' ] },
  { phrase: 'Good riddance', words: [ 'Good', 'riddance' ] },
  { phrase: 'Good Samaritan', words: [ 'Good', 'Samaritan' ] },
  { phrase: 'Goody two shoes', words: [ 'Goody', 'shoes' ] },
  { phrase: 'Gordon Bennett', words: [ 'Gordon', 'Bennett' ] },
  { phrase: 'Got my mojo working', words: [ 'mojo', 'working' ] },
  { phrase: 'Grand slam', words: [ 'Grand', 'slam' ] },
  { phrase: 'Grandfather clock',
    words: [ 'Grandfather', 'clock' ] },
  { phrase: 'Granny dumping', words: [ 'Granny', 'dumping' ] },
  { phrase: 'Grasp the nettle', words: [ 'Grasp', 'nettle' ] },
  { phrase: 'Graveyard shift', words: [ 'Graveyard', 'shift' ] },
  { phrase: 'Greased lightning',
    words: [ 'Greased', 'lightning' ] },
  { phrase: 'Great unwashed', words: [ 'Great', 'unwashed' ] },
  { phrase: 'Gregory Peck', words: [ 'Gregory', 'Peck' ] },
  { phrase: 'Grind to a halt', words: [ 'Grind', 'halt' ] },
  { phrase: 'Grist to the mill', words: [ 'Grist', 'mill' ] },
  { phrase: 'Guinea pig', words: [ 'Guinea', 'pig' ] },
  { phrase: 'Gung ho', words: [ 'Gung', 'ho' ] },
  { phrase: 'Guts for garters', words: [ 'Guts', 'garters' ] },
  { phrase: 'Hairy eyeball', words: [ 'Hairy', 'eyeball' ] },
  { phrase: 'Halcyon days', words: [ 'Halcyon', 'days' ] },
  { phrase: 'Hand over fist', words: [ 'Hand', 'fist' ] },
  { phrase: 'Hanky panky', words: [ 'Hanky', 'panky' ] },
  { phrase: 'Happy as a clam', words: [ 'Happy', 'clam' ] },
  { phrase: 'Happy as a sandboy', words: [ 'Happy', 'sandboy' ] },
  { phrase: 'Happy as Larry', words: [ 'Happy', 'Larry' ] },
  { phrase: 'Happy clappy', words: [ 'Happy', 'clappy' ] },
  { phrase: 'Happy slapping', words: [ 'Happy', 'slapping' ] },
  { phrase: 'Harbinger of doom', words: [ 'Harbinger', 'doom' ] },
  { phrase: 'Hard and fast', words: [ 'Hard', 'fast' ] },
  { phrase: 'Hard cheese', words: [ 'Hard', 'cheese' ] },
  { phrase: 'Hard hearted', words: [ 'Hard', 'hearted' ] },
  { phrase: 'Hard lines', words: [ 'Hard', 'lines' ] },
  { phrase: 'Hat trick', words: [ 'Hat', 'trick' ] },
  { phrase: 'Have a Captain Cook', words: [ 'Captain', 'Cook' ] },
  { phrase: 'Have an axe to grind', words: [ 'axe', 'grind' ] },
  { phrase: 'Haven\'t got a clue', words: [ 'Haven\'t', 'clue' ] },
  { phrase: 'Have your guts for garters',
    words: [ 'guts', 'garters' ] },
  { phrase: 'Head over heels', words: [ 'Head', 'heels' ] },
  { phrase: 'Hear hear', words: [ 'Hear', 'hear' ] },
  { phrase: 'Heart\'s content', words: [ 'Heart\'s', 'content' ] },
  { phrase: 'Heavens to Betsy', words: [ 'Heavens', 'Betsy' ] },
  { phrase: 'Heavens to Murgatroyd',
    words: [ 'Heavens', 'Murgatroyd' ] },
  { phrase: 'Heavy metal', words: [ 'Heavy', 'metal' ] },
  { phrase: 'Heebie jeebies', words: [ 'Heebie', 'jeebies' ] },
  { phrase: 'Hedge your bets', words: [ 'Hedge', 'bets' ] },
  { phrase: 'Hell or high water', words: [ 'high', 'water' ] },
  { phrase: 'Helter skelter', words: [ 'Helter', 'skelter' ] },
  { phrase: 'Hiding to nothing - On a', words: [ 'Hiding', '-' ] },
  { phrase: 'High and dry', words: [ 'High', 'dry' ] },
  { phrase: 'High and mighty', words: [ 'High', 'mighty' ] },
  { phrase: 'High flyer', words: [ 'High', 'flyer' ] },
  { phrase: 'High on the hog', words: [ 'High', 'hog' ] },
  { phrase: 'High time', words: [ 'High', 'time' ] },
  { phrase: 'Hissy fit', words: [ 'Hissy', 'fit' ] },
  { phrase: 'History is bunk', words: [ 'History', 'bunk' ] },
  { phrase: 'Hit the hay', words: [ 'Hit', 'hay' ] },
  { phrase: 'Hobson\'s choice', words: [ 'Hobson\'s', 'choice' ] },
  { phrase: 'Hobby horse', words: [ 'Hobby', 'horse' ] },
  { phrase: 'Hocus pocus', words: [ 'Hocus', 'pocus' ] },
  { phrase: 'Hoi polloi', words: [ 'Hoi', 'polloi' ] },
  { phrase: 'Hoist with your own petard',
    words: [ 'Hoist', 'petard' ] },
  { phrase: 'Hoity toity', words: [ 'Hoity', 'toity' ] },
  { phrase: 'Hold your horses', words: [ 'Hold', 'horses' ] },
  { phrase: 'Honesty is the best policy',
    words: [ 'Honesty', 'policy' ] },
  { phrase: 'Hooray Henry', words: [ 'Hooray', 'Henry' ] },
  { phrase: 'Horse and cart', words: [ 'Horse', 'cart' ] },
  { phrase: 'Horse feathers', words: [ 'Horse', 'feathers' ] },
  { phrase: 'Hot blooded', words: [ 'Hot', 'blooded' ] },
  { phrase: 'Hot off the press', words: [ 'Hot', 'press' ] },
  { phrase: 'Hot on the heels', words: [ 'Hot', 'heels' ] },
  { phrase: 'Household words', words: [ 'Household', 'words' ] },
  { phrase: 'Houston, we have a problem',
    words: [ 'Houston,', 'problem' ] },
  { phrase: 'How are the mighty fallen?',
    words: [ 'mighty', 'fallen?' ] },
  { phrase: 'How now brown cow?', words: [ 'brown', 'cow?' ] },
  { phrase: 'Hugger mugger', words: [ 'Hugger', 'mugger' ] },
  { phrase: 'Hunky dory', words: [ 'Hunky', 'dory' ] },
  { phrase: 'Hunt and peck', words: [ 'Hunt', 'peck' ] },
  { phrase: 'Hush puppies', words: [ 'Hush', 'puppies' ] },
  { phrase: 'I have not slept one wink',
    words: [ 'slept', 'wink' ] },
  { phrase: 'I haven\'t got a clue',
    words: [ 'haven\'t', 'clue' ] },
  { phrase: 'I spy with my little eye', words: [ 'spy', 'eye' ] },
  { phrase: 'Identity theft', words: [ 'Identity', 'theft' ] },
  { phrase: 'Indian giver', words: [ 'Indian', 'giver' ] },
  { phrase: 'Indian summer', words: [ 'Indian', 'summer' ] },
  { phrase: 'Infra dig', words: [ 'Infra', 'dig' ] },
  { phrase: 'Iron hoof', words: [ 'Iron', 'hoof' ] },
  { phrase: 'Is the Pope Catholic?',
    words: [ 'Pope', 'Catholic?' ] },
  { phrase: 'Is the Pope Polish?', words: [ 'Pope', 'Polish?' ] },
  { phrase: 'It is meat and drink to me',
    words: [ 'meat', 'drink' ] },
  { phrase: 'It\'s that man again', words: [ 'It\'s', 'man' ] },
  { phrase: 'Ivory tower', words: [ 'Ivory', 'tower' ] },
  { phrase: 'Jack in the box', words: [ 'Jack', 'box' ] },
  { phrase: 'Jack Palancing', words: [ 'Jack', 'Palancing' ] },
  { phrase: 'Jack the lad', words: [ 'Jack', 'lad' ] },
  { phrase: 'Jam tomorrow', words: [ 'Jam', 'tomorrow' ] },
  { phrase: 'Jerry built', words: [ 'Jerry', 'built' ] },
  { phrase: 'Jimmy Horner', words: [ 'Jimmy', 'Horner' ] },
  { phrase: 'Jimmy Riddle', words: [ 'Jimmy', 'Riddle' ] },
  { phrase: 'Jobs for the boys', words: [ 'Jobs', 'boys' ] },
  { phrase: 'Join the colours', words: [ 'Join', 'colours' ] },
  { phrase: 'Joined at the hip', words: [ 'Joined', 'hip' ] },
  { phrase: 'Johnny on the spot', words: [ 'Johnny', 'spot' ] },
  { phrase: 'Jot or tittle', words: [ 'Jot', 'tittle' ] },
  { phrase: 'Jump on the bandwagon',
    words: [ 'Jump', 'bandwagon' ] },
  { phrase: 'Jump the gun', words: [ 'Jump', 'gun' ] },
  { phrase: 'Jump the shark', words: [ 'Jump', 'shark' ] },
  { phrase: 'Kangaroo court', words: [ 'Kangaroo', 'court' ] },
  { phrase: 'Keep a wide berth', words: [ 'wide', 'berth' ] },
  { phrase: 'Keen as mustard', words: [ 'Keen', 'mustard' ] },
  { phrase: 'Keep the ball rolling',
    words: [ 'ball', 'rolling' ] },
  { phrase: 'Keep your hands clean', words: [ 'hands', 'clean' ] },
  { phrase: 'Keep your nose clean', words: [ 'nose', 'clean' ] },
  { phrase: 'Keep your powder dry', words: [ 'powder', 'dry' ] },
  { phrase: 'Keepy uppy', words: [ 'Keepy', 'uppy' ] },
  { phrase: 'Kettle of fish', words: [ 'Kettle', 'fish' ] },
  { phrase: 'Khyber pass', words: [ 'Khyber', 'pass' ] },
  { phrase: 'Kick the bucket', words: [ 'Kick', 'bucket' ] },
  { phrase: 'Kick your heels', words: [ 'Kick', 'heels' ] },
  { phrase: 'Kiss me Hardy', words: [ 'Kiss', 'Hardy' ] },
  { phrase: 'Knick knack', words: [ 'Knick', 'knack' ] },
  { phrase: 'Knock on wood', words: [ 'Knock', 'wood' ] },
  { phrase: 'Labour of love', words: [ 'Labour', 'love' ] },
  { phrase: 'Lager frenzy', words: [ 'Lager', 'frenzy' ] },
  { phrase: 'Laid out in lavender',
    words: [ 'Laid', 'lavender' ] },
  { phrase: 'Lamb to the slaughter',
    words: [ 'Lamb', 'slaughter' ] },
  { phrase: 'Lame duck', words: [ 'Lame', 'duck' ] },
  { phrase: 'Land of nod', words: [ 'Land', 'nod' ] },
  { phrase: 'Lardy dardy', words: [ 'Lardy', 'dardy' ] },
  { phrase: 'Latin Phrases', words: [ 'Latin', 'Phrases' ] },
  { phrase: 'Laugh like a drain', words: [ 'Laugh', 'drain' ] },
  { phrase: 'Laughing stock', words: [ 'Laughing', 'stock' ] },
  { phrase: 'The law is an ass', words: [ 'law', 'ass' ] },
  { phrase: 'Lay it on with a trowel',
    words: [ 'Lay', 'trowel' ] },
  { phrase: 'Learn the ropes', words: [ 'Learn', 'ropes' ] },
  { phrase: 'Left in the lurch', words: [ 'Left', 'lurch' ] },
  { phrase: 'Let bygones be bygones',
    words: [ 'bygones', 'bygones' ] },
  { phrase: 'Let the cat out of the bag',
    words: [ 'cat', 'bag' ] },
  { phrase: 'Let them eat cake', words: [ 'eat', 'cake' ] },
  { phrase: 'Let\'s roll', words: [ 'Let\'s', 'roll' ] },
  { phrase: 'Lick and a promise', words: [ 'Lick', 'promise' ] },
  { phrase: 'Lick into shape', words: [ 'Lick', 'shape' ] },
  { phrase: 'Lickety split', words: [ 'Lickety', 'split' ] },
  { phrase: 'Life of Riley', words: [ 'Life', 'Riley' ] },
  { phrase: 'Life\'s too short', words: [ 'Life\'s', 'short' ] },
  { phrase: 'Like a moth to a flame', words: [ 'moth', 'flame' ] },
  { phrase: 'Like two peas in a pod', words: [ 'peas', 'pod' ] },
  { phrase: 'Little bird told me', words: [ 'bird', 'told' ] },
  { phrase: 'Living daylights', words: [ 'Living', 'daylights' ] },
  { phrase: 'Lo and behold', words: [ 'Lo', 'behold' ] },
  { phrase: 'Load of cobblers', words: [ 'Load', 'cobblers' ] },
  { phrase: 'Load of codswallop',
    words: [ 'Load', 'codswallop' ] },
  { phrase: 'Loaf of bread', words: [ 'Loaf', 'bread' ] },
  { phrase: 'Local derby', words: [ 'Local', 'derby' ] },
  { phrase: 'Long in the tooth', words: [ 'Long', 'tooth' ] },
  { phrase: 'Loose cannon', words: [ 'Loose', 'cannon' ] },
  { phrase: 'Lose face', words: [ 'Lose', 'face' ] },
  { phrase: 'Lose your marbles', words: [ 'Lose', 'marbles' ] },
  { phrase: 'Love is blind', words: [ 'Love', 'blind' ] },
  { phrase: 'Mad as a hatter', words: [ 'Mad', 'hatter' ] },
  { phrase: 'Magical realism', words: [ 'Magical', 'realism' ] },
  { phrase: 'Main chance', words: [ 'Main', 'chance' ] },
  { phrase: 'Make a bee line for', words: [ 'bee', 'line' ] },
  { phrase: 'Make a clean breast of it',
    words: [ 'clean', 'breast' ] },
  { phrase: 'Make a pig\'s ear of', words: [ 'pig\'s', 'ear' ] },
  { phrase: 'Make a virtue of necessity',
    words: [ 'virtue', 'necessity' ] },
  { phrase: 'Man after my own heart', words: [ 'Man', 'heart' ] },
  { phrase: 'Many happy returns', words: [ 'happy', 'returns' ] },
  { phrase: 'Mare\'s nest', words: [ 'Mare\'s', 'nest' ] },
  { phrase: 'Marital aid', words: [ 'Marital', 'aid' ] },
  { phrase: 'Market forces', words: [ 'Market', 'forces' ] },
  { phrase: 'real McCoy', words: [ 'McCoy', 'real' ] },
  { phrase: 'Mea culpa', words: [ 'Mea', 'culpa' ] },
  { phrase: 'Meat and drink', words: [ 'Meat', 'drink' ] },
  { phrase: 'Meat and two veg.', words: [ 'Meat', 'veg.' ] },
  { phrase: 'Meet your Waterloo', words: [ 'Meet', 'Waterloo' ] },
  { phrase: 'Men in suits', words: [ 'Men', 'suits' ] },
  { phrase: 'Mend fences', words: [ 'Mend', 'fences' ] },
  { phrase: 'Merry Christmas', words: [ 'Merry', 'Christmas' ] },
  { phrase: 'Mexican wave', words: [ 'Mexican', 'wave' ] },
  { phrase: 'Mickey Finn', words: [ 'Mickey', 'Finn' ] },
  { phrase: 'Middle for diddle', words: [ 'Middle', 'diddle' ] },
  { phrase: 'Middle of the road', words: [ 'Middle', 'road' ] },
  { phrase: 'Minced oaths', words: [ 'Minced', 'oaths' ] },
  { phrase: 'Miss is as good as a mile',
    words: [ 'good', 'mile' ] },
  { phrase: 'Moaning Minnie', words: [ 'Moaning', 'Minnie' ] },
  { phrase: 'Montezuma\'s Revenge',
    words: [ 'Montezuma\'s', 'Revenge' ] },
  { phrase: 'Monty full', words: [ 'Monty', 'full' ] },
  { phrase: 'Moot point', words: [ 'Moot', 'point' ] },
  { phrase: 'Morbid obesity', words: [ 'Morbid', 'obesity' ] },
  { phrase: 'More bangs for your buck',
    words: [ 'bangs', 'buck' ] },
  { phrase: 'Morning person', words: [ 'Morning', 'person' ] },
  { phrase: 'Mother country', words: [ 'Mother', 'country' ] },
  { phrase: 'Motley crew', words: [ 'Motley', 'crew' ] },
  { phrase: 'Mouth watering', words: [ 'Mouth', 'watering' ] },
  { phrase: 'Moveable feast', words: [ 'Moveable', 'feast' ] },
  { phrase: 'Movers and shakers', words: [ 'Movers', 'shakers' ] },
  { phrase: 'Moving the goalposts',
    words: [ 'Moving', 'goalposts' ] },
  { phrase: 'Mud - your name is', words: [ 'Mud', '-' ] },
  { phrase: 'Multitude of sins', words: [ 'Multitude', 'sins' ] },
  { phrase: 'Mumbo jumbo', words: [ 'Mumbo', 'jumbo' ] },
  { phrase: 'Mum\'s the word', words: [ 'Mum\'s', 'word' ] },
  { phrase: 'Murphy\'s Law', words: [ 'Murphy\'s', 'Law' ] },
  { phrase: 'Mutt\'s nuts', words: [ 'Mutt\'s', 'nuts' ] },
  { phrase: 'Mutt and Jeff', words: [ 'Mutt', 'Jeff' ] },
  { phrase: 'My cup of tea', words: [ 'cup', 'tea' ] },
  { phrase: 'My cup runneth over', words: [ 'cup', 'runneth' ] },
  { phrase: 'My giddy aunt', words: [ 'giddy', 'aunt' ] },
  { phrase: 'My mind\'s eye', words: [ 'mind\'s', 'eye' ] },
  { phrase: 'My salad days', words: [ 'salad', 'days' ] },
  { phrase: 'My stars and garters',
    words: [ 'stars', 'garters' ] },
  { phrase: 'Namby pamby', words: [ 'Namby', 'pamby' ] },
  { phrase: 'Nation of shopkeepers',
    words: [ 'Nation', 'shopkeepers' ] },
  { phrase: 'Nautical phrases', words: [ 'Nautical', 'phrases' ] },
  { phrase: 'Nest egg', words: [ 'Nest', 'egg' ] },
  { phrase: 'Nest of vipers', words: [ 'Nest', 'vipers' ] },
  { phrase: 'Never knowingly undersold',
    words: [ 'knowingly', 'undersold' ] },
  { phrase: 'Never the twain shall meet',
    words: [ 'twain', 'meet' ] },
  { phrase: 'New kid on the block', words: [ 'kid', 'block' ] },
  { phrase: 'Nice as ninepence', words: [ 'Nice', 'ninepence' ] },
  { phrase: 'Night owl', words: [ 'Night', 'owl' ] },
  { phrase: 'Nip and tuck', words: [ 'Nip', 'tuck' ] },
  { phrase: 'Nip in the bud', words: [ 'Nip', 'bud' ] },
  { phrase: 'Nitty gritty', words: [ 'Nitty', 'gritty' ] },
  { phrase: 'No holds barred', words: [ 'holds', 'barred' ] },
  { phrase: 'No laughing matter',
    words: [ 'laughing', 'matter' ] },
  { phrase: 'No man is an island', words: [ 'man', 'island' ] },
  { phrase: 'No more cakes and ale?', words: [ 'cakes', 'ale?' ] },
  { phrase: 'No rest for the wicked',
    words: [ 'rest', 'wicked' ] },
  { phrase: 'No way, Jose', words: [ 'way,', 'Jose' ] },
  { phrase: 'Nod land of', words: [ 'Nod', 'land' ] },
  { phrase: 'Nosy parker', words: [ 'Nosy', 'parker' ] },
  { phrase: 'Not a dicky bird', words: [ 'dicky', 'bird' ] },
  { phrase: 'Not my cup of tea', words: [ 'cup', 'tea' ] },
  { phrase: 'Not rocket science', words: [ 'rocket', 'science' ] },
  { phrase: 'Not tonight Josephine',
    words: [ 'tonight', 'Josephine' ] },
  { phrase: 'Not worth the candle', words: [ 'worth', 'candle' ] },
  { phrase: 'Nth degree', words: [ 'Nth', 'degree' ] },
  { phrase: 'Nul points', words: [ 'Nul', 'points' ] },
  { phrase: 'O ye, of little faith', words: [ 'ye,', 'faith' ] },
  { phrase: 'Odds bodkins', words: [ 'Odds', 'bodkins' ] },
  { phrase: 'Offing - In the', words: [ 'Offing', '-' ] },
  { phrase: 'Okey dokey', words: [ 'Okey', 'dokey' ] },
  { phrase: 'On a wing and a prayer',
    words: [ 'wing', 'prayer' ] },
  { phrase: 'On Carey Street', words: [ 'Carey', 'Street' ] },
  { phrase: 'On queer street', words: [ 'queer', 'street' ] },
  { phrase: 'On the shoulders of giants',
    words: [ 'shoulders', 'giants' ] },
  { phrase: 'On your beam ends', words: [ 'beam', 'ends' ] },
  { phrase: 'Once in a blue moon', words: [ 'blue', 'moon' ] },
  { phrase: 'One fell swoop', words: [ 'fell', 'swoop' ] },
  { phrase: 'One stop shop', words: [ 'stop', 'shop' ] },
  { phrase: 'Oops a-daisy', words: [ 'Oops', 'a-daisy' ] },
  { phrase: 'Open season', words: [ 'Open', 'season' ] },
  { phrase: 'Out of sight, out of mind',
    words: [ 'sight,', 'mind' ] },
  { phrase: 'Out of the jaws of death',
    words: [ 'jaws', 'death' ] },
  { phrase: 'Oxo cube', words: [ 'Oxo', 'cube' ] },
  { phrase: 'Packed to the gunwales',
    words: [ 'Packed', 'gunwales' ] },
  { phrase: 'Paddle your own canoe',
    words: [ 'Paddle', 'canoe' ] },
  { phrase: 'Panic stations', words: [ 'Panic', 'stations' ] },
  { phrase: 'Paper tiger', words: [ 'Paper', 'tiger' ] },
  { phrase: 'Pass the buck', words: [ 'Pass', 'buck' ] },
  { phrase: 'Pearls before swine', words: [ 'Pearls', 'swine' ] },
  { phrase: 'Pears for your heirs', words: [ 'Pears', 'heirs' ] },
  { phrase: 'Peeping Tom', words: [ 'Peeping', 'Tom' ] },
  { phrase: 'Pell mell', words: [ 'Pell', 'mell' ] },
  { phrase: 'Pester power', words: [ 'Pester', 'power' ] },
  { phrase: 'Petty cash', words: [ 'Petty', 'cash' ] },
  { phrase: 'Picture perfect', words: [ 'Picture', 'perfect' ] },
  { phrase: 'Pies easy as', words: [ 'Pies', 'easy' ] },
  { phrase: 'Pie in the sky', words: [ 'Pie', 'sky' ] },
  { phrase: 'Piece of cake', words: [ 'Piece', 'cake' ] },
  { phrase: 'Piece of piss', words: [ 'Piece', 'piss' ] },
  { phrase: 'Piece of the action', words: [ 'Piece', 'action' ] },
  { phrase: 'Pig in a poke', words: [ 'Pig', 'poke' ] },
  { phrase: 'Pigeon chested', words: [ 'Pigeon', 'chested' ] },
  { phrase: 'Pig\'s back - on the', words: [ 'Pig\'s', '-' ] },
  { phrase: 'Pig\'s ear', words: [ 'Pig\'s', 'ear' ] },
  { phrase: 'Pig and whistle', words: [ 'Pig', 'whistle' ] },
  { phrase: 'Pigs might fly', words: [ 'Pigs', 'fly' ] },
  { phrase: 'Pin money', words: [ 'Pin', 'money' ] },
  { phrase: 'Pipe dream', words: [ 'Pipe', 'dream' ] },
  { phrase: 'Piping hot', words: [ 'Piping', 'hot' ] },
  { phrase: 'Plain sailing', words: [ 'Plain', 'sailing' ] },
  { phrase: 'Plates of meat', words: [ 'Plates', 'meat' ] },
  { phrase: 'Play by ear', words: [ 'Play', 'ear' ] },
  { phrase: 'Play it again Sam', words: [ 'Play', 'Sam' ] },
  { phrase: 'Pleased as Punch', words: [ 'Pleased', 'Punch' ] },
  { phrase: 'Plug ugly', words: [ 'Plug', 'ugly' ] },
  { phrase: 'Plugged nickel', words: [ 'Plugged', 'nickel' ] },
  { phrase: 'Poetic justice', words: [ 'Poetic', 'justice' ] },
  { phrase: 'Point and click', words: [ 'Point', 'click' ] },
  { phrase: 'Politically correct',
    words: [ 'Politically', 'correct' ] },
  { phrase: 'Point blank', words: [ 'Point', 'blank' ] },
  { phrase: 'Point to point', words: [ 'Point', 'point' ] },
  { phrase: 'Pommy bashing', words: [ 'Pommy', 'bashing' ] },
  { phrase: 'Pond life', words: [ 'Pond', 'life' ] },
  { phrase: 'Pony and trap', words: [ 'Pony', 'trap' ] },
  { phrase: 'Pop goes the weasel', words: [ 'Pop', 'weasel' ] },
  { phrase: 'Pork pies', words: [ 'Pork', 'pies' ] },
  { phrase: 'Pound of flesh', words: [ 'Pound', 'flesh' ] },
  { phrase: 'Power dressing', words: [ 'Power', 'dressing' ] },
  { phrase: 'Preaching to the choir',
    words: [ 'Preaching', 'choir' ] },
  { phrase: 'Press into service', words: [ 'Press', 'service' ] },
  { phrase: 'Prick up your ears', words: [ 'Prick', 'ears' ] },
  { phrase: 'Prime time', words: [ 'Prime', 'time' ] },
  { phrase: 'Primrose path', words: [ 'Primrose', 'path' ] },
  { phrase: 'Proverbs list of', words: [ 'Proverbs', 'list' ] },
  { phrase: 'Pull in your horns', words: [ 'Pull', 'horns' ] },
  { phrase: 'Pull out all the stops', words: [ 'Pull', 'stops' ] },
  { phrase: 'Pull up stakes', words: [ 'Pull', 'stakes' ] },
  { phrase: 'Pull your horns in', words: [ 'Pull', 'horns' ] },
  { phrase: 'Purple patch', words: [ 'Purple', 'patch' ] },
  { phrase: 'Push the boat out', words: [ 'Push', 'boat' ] },
  { phrase: 'Push the envelope', words: [ 'Push', 'envelope' ] },
  { phrase: 'Put a damper on', words: [ 'Put', 'damper' ] },
  { phrase: 'Put a sock in it', words: [ 'Put', 'sock' ] },
  { phrase: 'Put paid to', words: [ 'Put', 'paid' ] },
  { phrase: 'Put the mockers on', words: [ 'Put', 'mockers' ] },
  { phrase: 'Put up your dukes', words: [ 'Put', 'dukes' ] },
  { phrase: 'Put your best foot forward',
    words: [ 'Put', 'foot' ] },
  { phrase: 'Pyrric victory', words: [ 'Pyrric', 'victory' ] },
  { phrase: 'Quality time', words: [ 'Quality', 'time' ] },
  { phrase: 'Queer Street', words: [ 'Queer', 'Street' ] },
  { phrase: 'Queer the pitch', words: [ 'Queer', 'pitch' ] },
  { phrase: 'Quick and the dead', words: [ 'Quick', 'dead' ] },
  { phrase: 'Rabbit and pork', words: [ 'Rabbit', 'pork' ] },
  { phrase: 'Rack and ruin', words: [ 'Rack', 'ruin' ] },
  { phrase: 'Rack your brains', words: [ 'Rack', 'brains' ] },
  { phrase: 'Raise Cain', words: [ 'Raise', 'Cain' ] },
  { phrase: 'Rank and file', words: [ 'Rank', 'file' ] },
  { phrase: 'Raspberry tart', words: [ 'Raspberry', 'tart' ] },
  { phrase: 'Raze to the ground', words: [ 'Raze', 'ground' ] },
  { phrase: 'Rat arsed', words: [ 'Rat', 'arsed' ] },
  { phrase: 'Read between the lines', words: [ 'Read', 'lines' ] },
  { phrase: 'Real McCoy', words: [ 'Real', 'McCoy' ] },
  { phrase: 'Red handed', words: [ 'Red', 'handed' ] },
  { phrase: 'Red herring', words: [ 'Red', 'herring' ] },
  { phrase: 'Red tape', words: [ 'Red', 'tape' ] },
  { phrase: 'Reduplicated phrases',
    words: [ 'Reduplicated', 'phrases' ] },
  { phrase: 'Rest on his laurels', words: [ 'Rest', 'laurels' ] },
  { phrase: 'Rhyme nor reason', words: [ 'Rhyme', 'reason' ] },
  { phrase: 'Rhyming slang', words: [ 'Rhyming', 'slang' ] },
  { phrase: 'Riding shotgun', words: [ 'Riding', 'shotgun' ] },
  { phrase: 'Riff raff', words: [ 'Riff', 'raff' ] },
  { phrase: 'Riley life of', words: [ 'Riley', 'life' ] },
  { phrase: 'Ring down the curtain',
    words: [ 'Ring', 'curtain' ] },
  { phrase: 'Ring fencing', words: [ 'Ring', 'fencing' ] },
  { phrase: 'Rinky dink', words: [ 'Rinky', 'dink' ] },
  { phrase: 'Rise and shine', words: [ 'Rise', 'shine' ] },
  { phrase: 'Road less travelled',
    words: [ 'Road', 'travelled' ] },
  { phrase: 'Road apples', words: [ 'Road', 'apples' ] },
  { phrase: 'Road rage', words: [ 'Road', 'rage' ] },
  { phrase: 'Roasted to a turn', words: [ 'Roasted', 'turn' ] },
  { phrase: 'Rock and roll', words: [ 'Rock', 'roll' ] },
  { phrase: 'Rosie Lea', words: [ 'Rosie', 'Lea' ] },
  { phrase: 'Rough diamond', words: [ 'Rough', 'diamond' ] },
  { phrase: 'Rub of the green', words: [ 'Rub', 'green' ] },
  { phrase: 'Rule of thumb', words: [ 'Rule', 'thumb' ] },
  { phrase: 'Rumpy pumpy', words: [ 'Rumpy', 'pumpy' ] },
  { phrase: 'Run a mile', words: [ 'Run', 'mile' ] },
  { phrase: 'Run amok', words: [ 'Run', 'amok' ] },
  { phrase: 'Run of the mill', words: [ 'Run', 'mill' ] },
  { phrase: 'Run out of steam', words: [ 'Run', 'steam' ] },
  { phrase: 'Run rings around', words: [ 'Run', 'rings' ] },
  { phrase: 'Run the gauntlet', words: [ 'Run', 'gauntlet' ] },
  { phrase: 'Sacred cow', words: [ 'Sacred', 'cow' ] },
  { phrase: 'Safe sex', words: [ 'Safe', 'sex' ] },
  { phrase: 'Salad days', words: [ 'Salad', 'days' ] },
  { phrase: 'Salt of the earth', words: [ 'Salt', 'earth' ] },
  { phrase: 'Save face', words: [ 'Save', 'face' ] },
  { phrase: 'Saved by the bell', words: [ 'Saved', 'bell' ] },
  { phrase: 'Savoir faire', words: [ 'Savoir', 'faire' ] },
  { phrase: 'Say goodnight Gracie',
    words: [ 'goodnight', 'Gracie' ] },
  { phrase: 'Scot free', words: [ 'Scot', 'free' ] },
  { phrase: 'Sea change', words: [ 'Sea', 'change' ] },
  { phrase: 'Security blanket', words: [ 'Security', 'blanket' ] },
  { phrase: 'Send packing', words: [ 'Send', 'packing' ] },
  { phrase: 'Senior citizen', words: [ 'Senior', 'citizen' ] },
  { phrase: 'Sex and shopping', words: [ 'Sex', 'shopping' ] },
  { phrase: 'Seven year itch', words: [ 'year', 'itch' ] },
  { phrase: 'Sexton Blake', words: [ 'Sexton', 'Blake' ] },
  { phrase: 'Shake a leg', words: [ 'Shake', 'leg' ] },
  { phrase: 'Shakers and movers', words: [ 'Shakers', 'movers' ] },
  { phrase: 'Shilly shally', words: [ 'Shilly', 'shally' ] },
  { phrase: 'Shit for brains', words: [ 'Shit', 'brains' ] },
  { phrase: 'Shiver my timbers', words: [ 'Shiver', 'timbers' ] },
  { phrase: 'Shot across the bows', words: [ 'Shot', 'bows' ] },
  { phrase: 'Shot in the arm', words: [ 'Shot', 'arm' ] },
  { phrase: 'Shot in the dark', words: [ 'Shot', 'dark' ] },
  { phrase: 'Short shrift', words: [ 'Short', 'shrift' ] },
  { phrase: 'Show your mettle', words: [ 'Show', 'mettle' ] },
  { phrase: 'Sick puppy', words: [ 'Sick', 'puppy' ] },
  { phrase: 'Silly Billy', words: [ 'Silly', 'Billy' ] },
  { phrase: 'Silly season', words: [ 'Silly', 'season' ] },
  { phrase: 'Silence is golden', words: [ 'Silence', 'golden' ] },
  { phrase: 'Silver bullet', words: [ 'Silver', 'bullet' ] },
  { phrase: 'Sixes and sevens', words: [ 'Sixes', 'sevens' ] },
  { phrase: 'Skeleton in the closet',
    words: [ 'Skeleton', 'closet' ] },
  { phrase: 'Skid row', words: [ 'Skid', 'row' ] },
  { phrase: 'Skin and blister', words: [ 'Skin', 'blister' ] },
  { phrase: 'Sleep like a top', words: [ 'Sleep', 'top' ] },
  { phrase: 'Sleep on a clothesline',
    words: [ 'Sleep', 'clothesline' ] },
  { phrase: 'Sleep tight', words: [ 'Sleep', 'tight' ] },
  { phrase: 'Sloane Ranger', words: [ 'Sloane', 'Ranger' ] },
  { phrase: 'Slush fund', words: [ 'Slush', 'fund' ] },
  { phrase: 'Smart casual', words: [ 'Smart', 'casual' ] },
  { phrase: 'Smoke and mirrors', words: [ 'Smoke', 'mirrors' ] },
  { phrase: 'Soap dodger', words: [ 'Soap', 'dodger' ] },
  { phrase: 'Sod\'s Law', words: [ 'Sod\'s', 'Law' ] },
  { phrase: 'Sold down the river', words: [ 'Sold', 'river' ] },
  { phrase: 'Son of a gun', words: [ 'Son', 'gun' ] },
  { phrase: 'Sound bite', words: [ 'Sound', 'bite' ] },
  { phrase: 'Sour grapes', words: [ 'Sour', 'grapes' ] },
  { phrase: 'Speak of the Devil', words: [ 'Speak', 'Devil' ] },
  { phrase: 'Special relationship',
    words: [ 'Special', 'relationship' ] },
  { phrase: 'Spelling bee', words: [ 'Spelling', 'bee' ] },
  { phrase: 'Spend a penny', words: [ 'Spend', 'penny' ] },
  { phrase: 'Spick and span', words: [ 'Spick', 'span' ] },
  { phrase: 'Spill the beans', words: [ 'Spill', 'beans' ] },
  { phrase: 'Spin doctor', words: [ 'Spin', 'doctor' ] },
  { phrase: 'Spitting feathers',
    words: [ 'Spitting', 'feathers' ] },
  { phrase: 'Spitting image', words: [ 'Spitting', 'image' ] },
  { phrase: 'Square meal', words: [ 'Square', 'meal' ] },
  { phrase: 'Stand and deliver', words: [ 'Stand', 'deliver' ] },
  { phrase: 'Stand up guy', words: [ 'Stand', 'guy' ] },
  { phrase: 'Stars and garters', words: [ 'Stars', 'garters' ] },
  { phrase: 'Start from scratch', words: [ 'Start', 'scratch' ] },
  { phrase: 'Steal a march', words: [ 'Steal', 'march' ] },
  { phrase: 'Steal my thunder', words: [ 'Steal', 'thunder' ] },
  { phrase: 'Stick in the mud', words: [ 'Stick', 'mud' ] },
  { phrase: 'Sticky wicket', words: [ 'Sticky', 'wicket' ] },
  { phrase: 'Stiffen the sinews', words: [ 'Stiffen', 'sinews' ] },
  { phrase: 'Stinking rich', words: [ 'Stinking', 'rich' ] },
  { phrase: 'Stone the crows', words: [ 'Stone', 'crows' ] },
  { phrase: 'Stone\'s throw', words: [ 'Stone\'s', 'throw' ] },
  { phrase: 'Stony hearted', words: [ 'Stony', 'hearted' ] },
  { phrase: 'Stool pigeon', words: [ 'Stool', 'pigeon' ] },
  { phrase: 'Storm in a teacup', words: [ 'Storm', 'teacup' ] },
  { phrase: 'Straight as a die', words: [ 'Straight', 'die' ] },
  { phrase: 'Strain at the leash', words: [ 'Strain', 'leash' ] },
  { phrase: 'Strait laced', words: [ 'Strait', 'laced' ] },
  { phrase: 'Strait and narrow', words: [ 'Strait', 'narrow' ] },
  { phrase: 'Stranger danger', words: [ 'Stranger', 'danger' ] },
  { phrase: 'Stuff and nonsense', words: [ 'Stuff', 'nonsense' ] },
  { phrase: 'Surf and turf', words: [ 'Surf', 'turf' ] },
  { phrase: 'Surfing the Net', words: [ 'Surfing', 'Net' ] },
  { phrase: 'surfing the Internet',
    words: [ 'surfing', 'Internet' ] },
  { phrase: 'surfing the Web', words: [ 'surfing', 'Web' ] },
  { phrase: 'Survival of the fittest',
    words: [ 'Survival', 'fittest' ] },
  { phrase: 'Suspension of disbelief',
    words: [ 'Suspension', 'disbelief' ] },
  { phrase: 'Swan song', words: [ 'Swan', 'song' ] },
  { phrase: 'Talk to the hand', words: [ 'Talk', 'hand' ] },
  { phrase: 'Tall story', words: [ 'Tall', 'story' ] },
  { phrase: 'Tea leaf', words: [ 'Tea', 'leaf' ] },
  { phrase: 'Tempest in a teapot',
    words: [ 'Tempest', 'teapot' ] },
  { phrase: 'Thick and thin', words: [ 'Thick', 'thin' ] },
  { phrase: 'Thinking cap', words: [ 'Thinking', 'cap' ] },
  { phrase: 'Thorn in the flesh', words: [ 'Thorn', 'flesh' ] },
  { phrase: 'Throw in the towel', words: [ 'Throw', 'towel' ] },
  { phrase: 'Tickle the ivories', words: [ 'Tickle', 'ivories' ] },
  { phrase: 'Tickled pink', words: [ 'Tickled', 'pink' ] },
  { phrase: 'Tie the knot', words: [ 'Tie', 'knot' ] },
  { phrase: 'To beggar belief', words: [ 'beggar', 'belief' ] },
  { phrase: 'Toast of the town', words: [ 'Toast', 'town' ] },
  { phrase: 'Toe the line', words: [ 'Toe', 'line' ] },
  { phrase: 'Toe curling', words: [ 'Toe', 'curling' ] },
  { phrase: 'Toffee nosed', words: [ 'Toffee', 'nosed' ] },
  { phrase: 'Tongue in cheek', words: [ 'Tongue', 'cheek' ] },
  { phrase: 'Toodle oo', words: [ 'Toodle', 'oo' ] },
  { phrase: 'Top dog', words: [ 'Top', 'dog' ] },
  { phrase: 'Top drawer', words: [ 'Top', 'drawer' ] },
  { phrase: 'Top notch', words: [ 'Top', 'notch' ] },
  { phrase: 'Topsy turvy', words: [ 'Topsy', 'turvy' ] },
  { phrase: 'Total shambles', words: [ 'Total', 'shambles' ] },
  { phrase: 'Touch wood', words: [ 'Touch', 'wood' ] },
  { phrase: 'Touchy feely', words: [ 'Touchy', 'feely' ] },
  { phrase: 'Tower of strength', words: [ 'Tower', 'strength' ] },
  { phrase: 'Train surfing', words: [ 'Train', 'surfing' ] },
  { phrase: 'Trick or treat', words: [ 'Trick', 'treat' ] },
  { phrase: 'Trouble and strife', words: [ 'Trouble', 'strife' ] },
  { phrase: 'True blue', words: [ 'True', 'blue' ] },
  { phrase: 'Turn of phrase', words: [ 'Turn', 'phrase' ] },
  { phrase: 'Turn the tables', words: [ 'Turn', 'tables' ] },
  { phrase: 'peas in a pod', words: [ 'peas', 'pod' ] },
  { phrase: 'apples and pears', words: [ 'apples', 'pears' ] },
  { phrase: 'Upper crust', words: [ 'Upper', 'crust' ] },
  { phrase: 'Upper hand', words: [ 'Upper', 'hand' ] },
  { phrase: 'Urban myth', words: [ 'Urban', 'myth' ] },
  { phrase: 'Usual suspects', words: [ 'Usual', 'suspects' ] },
  { phrase: 'Vice versa', words: [ 'Vice', 'versa' ] },
  { phrase: 'Vicious circle', words: [ 'Vicious', 'circle' ] },
  { phrase: 'Walk free', words: [ 'Walk', 'free' ] },
  { phrase: 'Walk the plank', words: [ 'Walk', 'plank' ] },
  { phrase: 'Wax lyrical', words: [ 'Wax', 'lyrical' ] },
  { phrase: 'Wax poetic', words: [ 'Wax', 'poetic' ] },
  { phrase: 'Weakest link', words: [ 'Weakest', 'link' ] },
  { phrase: 'Weasel words', words: [ 'Weasel', 'words' ] },
  { phrase: 'Wee wee', words: [ 'Wee', 'wee' ] },
  { phrase: 'When pigs fly', words: [ 'pigs', 'fly' ] },
  { phrase: 'Whet your appetite', words: [ 'Whet', 'appetite' ] },
  { phrase: 'Whistle and flute', words: [ 'Whistle', 'flute' ] },
  { phrase: 'White bread', words: [ 'White', 'bread' ] },
  { phrase: 'Whipper snapper', words: [ 'Whipper', 'snapper' ] },
  { phrase: 'Whipping boy', words: [ 'Whipping', 'boy' ] },
  { phrase: 'White elephant', words: [ 'White', 'elephant' ] },
  { phrase: 'Willy nilly', words: [ 'Willy', 'nilly' ] },
  { phrase: 'Worse for wear', words: [ 'Worse', 'wear' ] },
  { phrase: 'Young turk', words: [ 'Young', 'turk' ] },
  { phrase: 'Zig zag', words: [ 'Zig', 'zag' ] } ]
